/-
  IP.Crypto.AESGCM — AES-128 GCM AEAD (NIST SP 800-38D §7).

  GCM = AES-CTR for confidentiality + GHASH for integrity,
  with the hash subkey H = AES(K, 0) and the initial
  counter J_0 derived from the IV.  For the standard
  96-bit IV path, J_0 = IV || 0x00000001.

  This file ships the pure-data reference (encrypt /
  decrypt-and-verify) on top of `IP.Crypto.AES` and
  `IP.Crypto.GHASH`.  Validated against NIST GCM Test
  Cases 1, 2, 3 from SP 800-38D Appendix B.

  TLS 1.3 record protection uses AEAD_AES_128_GCM
  (RFC 8446 §5.2), which is exactly this construction with
  a 12-byte IV and 16-byte authentication tag.
-/

import IP.Crypto.Codec.AES
import IP.Crypto.Codec.GHASH

namespace Sparkle.IP.Crypto.AESGCM

open Sparkle.IP.Crypto.AES (encryptBlock)
open Sparkle.IP.Crypto.GHASH
  (R gmul ghashBlocks bytesToBlock blockToBytes bytesToPaddedBlocks lenBlock ghashFull)

/-! ### Counter helpers. -/

/-- inc32: add 1 (mod 2^32) to the low 32 bits of a 128-bit
    block, leaving the high 96 bits unchanged.  NIST §6.2. -/
def inc32 (block : BitVec 128) : BitVec 128 :=
  let n := block.toNat
  let mask32 := (1 <<< 32) - 1
  let high96 := n >>> 32
  let lowOld := n &&& mask32
  let low32 := (lowOld + 1) &&& mask32
  BitVec.ofNat 128 ((high96 <<< 32) ||| low32)

/-- Derive the initial counter J_0 from K and IV per NIST §7.1.
    96-bit IV path: J_0 = IV || 0x00000001.
    General path  : J_0 = GHASH(H, IV || 0^s || len(IV)_{64}). -/
def deriveJ0 (h : BitVec 128) (iv : Array UInt8) : BitVec 128 :=
  if iv.size = 12 then
    -- 96-bit IV: J_0 = IV || 0x00000001
    let ivBlock := bytesToBlock (iv ++ #[0, 0, 0, 1])
    ivBlock
  else
    -- General IV: GHASH over padded IV + length block
    let blocks := bytesToPaddedBlocks iv
    let lb := lenBlock 0 (iv.size * 8)
    ghashBlocks h (blocks ++ [lb])

/-! ### AES-CTR. -/

/-- XOR a byte array with `keystream`. -/
private def xorBytes (a b : Array UInt8) : Array UInt8 := Id.run do
  let n := a.size
  let mut out : Array UInt8 := Array.replicate n 0
  for i in [:n] do
    let bi := if h : i < b.size then b[i]! else 0
    out := out.set! i (a[i]! ^^^ bi)
  return out

/-- AES-CTR encrypt/decrypt (symmetric): XOR input with
    keystream blocks generated by AES(K, counter_i) for
    successive `inc32`s starting from `startCounter`. -/
def aesCtr (key : Array UInt8) (startCounter : BitVec 128)
    (input : Array UInt8) : Array UInt8 := Id.run do
  let n := input.size
  let mut out : Array UInt8 := Array.replicate n 0
  let mut counter := startCounter
  let mut offset := 0
  while offset < n do
    let counterBytes := blockToBytes counter
    let keystream := encryptBlock key counterBytes
    let remaining := n - offset
    let take := if remaining < 16 then remaining else 16
    for i in [:take] do
      out := out.set! (offset + i) (input[offset + i]! ^^^ keystream[i]!)
    counter := inc32 counter
    offset := offset + 16
  return out

/-! ### AES-GCM encrypt / decrypt. -/

structure GcmCiphertext where
  ciphertext : Array UInt8
  tag        : Array UInt8   -- 16 bytes
  deriving Repr

/-- AES-128-GCM encrypt-and-authenticate per NIST §7.1.
    Returns (C, T) where T is the 128-bit tag.

    Standard AEAD signature: GCM-AE_K(IV, P, AAD). -/
def encryptAead (key iv plaintext aad : Array UInt8) : GcmCiphertext := Id.run do
  -- 1. Hash subkey H = AES_K(0).
  let zeroBlock : Array UInt8 := Array.replicate 16 0
  let h := bytesToBlock (encryptBlock key zeroBlock)
  -- 2. Initial counter J_0.
  let j0 := deriveJ0 h iv
  -- 3. CTR encrypt starting from inc32(J_0).
  let c := aesCtr key (inc32 j0) plaintext
  -- 4. GHASH over (AAD || pad || C || pad || lenBlock).
  let s := ghashFull h aad c
  -- 5. Tag T = AES_K(J_0) XOR S.
  let ekJ0 := encryptBlock key (blockToBytes j0)
  let sBytes := blockToBytes s
  let tag := xorBytes ekJ0 sBytes
  return { ciphertext := c, tag := tag }

/-- AES-128-GCM decrypt-and-verify per NIST §7.2.
    Returns `some plaintext` on success, `none` on tag mismatch. -/
def decryptAead (key iv ciphertext aad tag : Array UInt8) :
    Option (Array UInt8) := Id.run do
  let zeroBlock : Array UInt8 := Array.replicate 16 0
  let h := bytesToBlock (encryptBlock key zeroBlock)
  let j0 := deriveJ0 h iv
  -- Compute expected tag T' first (constant-time-ish: always
  -- run GHASH + CTR, then compare).
  let s := ghashFull h aad ciphertext
  let ekJ0 := encryptBlock key (blockToBytes j0)
  let sBytes := blockToBytes s
  let tagExp := xorBytes ekJ0 sBytes
  -- Constant-ish-time tag compare.
  if tagExp.size ≠ tag.size then return none
  let mut diff : UInt8 := 0
  for i in [:tagExp.size] do
    diff := diff ||| (tagExp[i]! ^^^ tag[i]!)
  if diff ≠ 0 then
    return none
  -- Tag OK — decrypt via CTR starting from inc32(J_0).
  let p := aesCtr key (inc32 j0) ciphertext
  return some p

end Sparkle.IP.Crypto.AESGCM
