window.BENCHMARK_DATA = {
  "lastUpdate": 1778552800833,
  "repoUrl": "https://github.com/Verilean/sparkle",
  "entries": {
    "RV32 SoC Simulation Benchmark (Verilator vs JIT)": [
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "013443ba59c63ef7a13f40270d2db4230cbb4a0e",
          "message": "ci: preserve benchmark JSON across git stash",
          "timestamp": "2026-03-26T12:24:42+09:00",
          "tree_id": "2c4e9dd57e4df348ac816af39b6d0bb5e2192a7f",
          "url": "https://github.com/Verilean/sparkle/commit/013443ba59c63ef7a13f40270d2db4230cbb4a0e"
        },
        "date": 1774495789741,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3285506,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4856146,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5465489,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4968426,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "e1c53641a220e3c602c86ab73517f8ed8ea92f93",
          "message": "Merge pull request #14 from Verilean/feature/rv32\n\nci: preserve benchmark JSON across git stash",
          "timestamp": "2026-03-26T12:25:40+09:00",
          "tree_id": "2c4e9dd57e4df348ac816af39b6d0bb5e2192a7f",
          "url": "https://github.com/Verilean/sparkle/commit/e1c53641a220e3c602c86ab73517f8ed8ea92f93"
        },
        "date": 1774495849619,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3280838,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4946544,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5469307,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4978734,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "53a9286586ccf563348df73fe880d1ef03168d06",
          "message": "chore: gitignore verilator/generated_soc_cppsim.h build artifact\n\nCompanion to the already-ignored generated_soc_jit.cpp. Both files are\nregenerated by 'lake build IP.RV32.SoCVerilog'.",
          "timestamp": "2026-04-08T21:37:07+09:00",
          "tree_id": "6ae8e82310e17eae00d05dd6634a5eeda1dc362b",
          "url": "https://github.com/Verilean/sparkle/commit/53a9286586ccf563348df73fe880d1ef03168d06"
        },
        "date": 1775652117939,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3829037,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3812284,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5145965,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4928097,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "cd9d63c2b01a6e7249288598dc50548bbd292ace",
          "message": "fix(CppSim): dedupe statement declarations by identifier\n\nLiteX-style Verilog patterns like\n\n    reg [9:0] storage_1_dat0;\n    always @(posedge clk)\n        storage_1_dat0 <= storage_1[addr];\n\nsurface in the IR as both a `.memory` read-data port and a standalone\n`.register` statement with the same name. emitModule then emitted two\nclass member declarations for the same identifier (different types,\nbecause the register path falls back to 32-bit when the name is missing\nfrom typeMap), producing invalid C++:\n\n    uint16_t storage_1_dat0;  // from memory\n    uint32_t storage_1_dat0;  // from register ← redeclaration error\n\nFix: after collecting `stmtDecls` from all statement emissions, dedupe\nby extracting the trailing identifier token and keeping the first\noccurrence. Memory read-data ports are emitted before the register\nfallback and already carry the correct dataWidth, so keeping the first\ncopy is the right choice.\n\nThis unblocks the LiteX JIT build in GitHub Actions (the CI step that\ncompiles /tmp/litex_jit.cpp was failing with\n'redeclaration of storage_1_dat0').",
          "timestamp": "2026-04-08T21:53:38+09:00",
          "tree_id": "6fec48d398a43ee54d1b8c7082704eb5ecd1b626",
          "url": "https://github.com/Verilean/sparkle/commit/cd9d63c2b01a6e7249288598dc50548bbd292ace"
        },
        "date": 1775655549066,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3301683,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4015768,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4454551,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4165818,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "ea311047a122960080f86586ec21f47716d6d6a9",
          "message": "Merge pull request #18 from Verilean/feature/rv32\n\nImprove JIT performance",
          "timestamp": "2026-04-08T22:52:17+09:00",
          "tree_id": "6fec48d398a43ee54d1b8c7082704eb5ecd1b626",
          "url": "https://github.com/Verilean/sparkle/commit/ea311047a122960080f86586ec21f47716d6d6a9"
        },
        "date": 1775656589024,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3717741,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4619606,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5162463,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4933481,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "87821d4b04a99a5699a7d7d8de6dc2499a47831f",
          "message": "fix(ci): build CppSim/SVParser oleans before LiteX JIT lean --run\n\n`lake env lean --run` reads existing .olean files without rebuilding.\nWhen GitHub Actions' cache predates a toolchain bump the oleans become\nstale and the runner fails with:\n\n    error: failed to read file 'Tools/SVParser.olean', incompatible header\n\nExplicitly `lake build Tools.SVParser Sparkle.Backend.CppSim` before\nthe `lake env lean --run` so the oleans are guaranteed to match the\ncurrent Lean version.",
          "timestamp": "2026-04-08T23:04:06+09:00",
          "tree_id": "1db9b60e7e8b468298fe3db6c1092c379f70b8f9",
          "url": "https://github.com/Verilean/sparkle/commit/87821d4b04a99a5699a7d7d8de6dc2499a47831f"
        },
        "date": 1775657354926,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3276518,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4050359,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4510850,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4158783,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "34ef705062ce838956a7dd70f2f2315a00567598",
          "message": "feat(sim): add runSim auto-dispatcher for multi-domain simulation\n\nIntroduces `Sparkle.Core.SimParallel` with a single high-level entry\npoint, `runSim`, that automatically picks the fastest backend based on\nthe number of endpoints and connections passed:\n\n  [ep]                            → runSingleSim (single-threaded evalTick)\n  [prod, cons], [(out, in)]       → runMultiDomainSim (JIT.runCDC, CDC queue)\n\nAll other combinations are rejected with a clear error message pointing\nat KnownIssues 3.1 (multi-connection) or 3.2 (3+ endpoints). The two\nbackends are also exposed as `runSingleSim` / `runMultiDomainSim` for\nusers who want to force a specific strategy.\n\nTyped endpoint creation:\n  - `sim!` and `generateSimWrappers` now emit per-module\n    `outputPortIndexByName`, `inputPortIndexByName`, `outputPortNames`,\n    `inputPortNames`, and `Simulator.toEndpoint`, so connections are\n    resolved by string name at runtime with clear errors for typos or\n    missing ports.\n  - `PortSpec` gains a `rawIndex` field so the typed layer stores the\n    exact raw JIT switch index. Manual `SimSpec` without explicit\n    rawIndex falls back to positional ordering.\n  - `SimMacro.lean` filters reset-like names from the user-facing\n    `SimInput` but keeps the raw-JIT index for surviving ports, fixing\n    a latent bug where `sim.step` would set the wrong port whenever a\n    reset wire was declared in the Verilog.\n\nRegression coverage — Tests/Sim/SimRunnerTest.lean (NEW, 27 tests):\n  A1–A4  Equivalence: runSim / runSingleSim / manual evalTick give\n         identical register snapshots; CDC relay transfers messages.\n  B1–B6  Auto-select: 1-ep → single path; 2-ep+1-conn → CDC path;\n         all illegal shapes are rejected.\n  C1–C5  Port-name resolution: unknown output/input, case sensitivity,\n         empty string, valid lookup round-trip.\n  D1–D4  Typed-vs-raw index alignment on DomainA (enable) and\n         DomainB (value, acc, acc2), including CDC via the non-default\n         port (count2, raw index 1).\n  E1–E5  Stress: 0 / 1 / 100 k cycles, double-run continuity, reset\n         between runs.\n\nEquivalence tests compare *all* registers via a `JIT.getReg` loop, not\njust observable outputs.\n\nTests/CDC/MultiClockTest.lean has been ported to the new API and still\npasses end-to-end (100 k messages transferred via runSim auto-dispatch).\n\nDocs:\n  - Tutorial Step 6 rewritten around runSim with single-domain and\n    multi-domain examples.\n  - KnownIssues Issue 3 marked Resolved; Issue 3.1 (multi-connection)\n    and Issue 3.2 (3+ endpoints) broken out as residual tracked items.\n  - STATUS Phase 5.6 marked Done.\n\nBuild & test:\n  lake build                                 green\n  lake exe svparser-test                     34/34\n  lake exe sim-runner-test                   27/27   (new)\n  lake exe cdc-multi-clock-test              PASS    (ported)",
          "timestamp": "2026-04-08T23:42:16+09:00",
          "tree_id": "17933a5a6243333d950fe52756f4d2a8382cf67f",
          "url": "https://github.com/Verilean/sparkle/commit/34ef705062ce838956a7dd70f2f2315a00567598"
        },
        "date": 1775659787546,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3289702,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4155100,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4543626,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4191644,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "fae81e36e24a60c4ac3730849fca861e8439bdfd",
          "message": "refactor: purge dead optimization scaffolding exposed by Issue 1 / 6\n\nFive small cleanups, net -92 lines, no behavior change.\n\n1. Delete wrapConditionalGuards in Sparkle/Backend/CppSim.lean.\n   The enable-signal / prefix-matching guard heuristic was bypassed\n   entirely in the Issue 6 fix (`let _ := wrapConditionalGuards`).\n   Remove the 70+ line function, its helper tables, and the bypass.\n   Replaced with a short comment explaining why the idea is unsound.\n\n2. Remove isSelfRef detection from the `.register` emitStmt branch.\n   With all evalTick _next locals now initialized to the current\n   register value (Issue 1 fix), the `findDeepestElse` / isSelfRef\n   computation no longer influences correctness, and the minArms=2\n   short-circuit for shallow self-ref mux chains is redundant with\n   Clang -O2's dead-store elimination. Use minArms=16 uniformly.\n   Also merges the two nearly-identical `if ifElseLines then … else …`\n   branches into one record.\n\n3. Delete isDebugSignal (CppSim.lean). It was already a no-op\n   (`_name : String => false`) once reachability DCE took over the\n   job in Lower.lean. Remove the def and its two call sites.\n\n4. Mark Signal.unbundle2 / unbundle3 / unbundle4 @[deprecated] with\n   since:=2026-04-08. They silently break in synthesis when\n   pattern-matched (returning Lean-level tuples); the preferred\n   Signal.fst/snd/proj3_*/proj4_* have long been available.\n\n5. Simplify dedupBody in Sparkle/IR/Optimize.lean to a single forward\n   pass that accumulates the result list directly, instead of a\n   two-pass index-drop scheme with two HashMaps. Semantics unchanged:\n   drop identity assigns and exact-duplicate repeats; keep later\n   assigns with a different rhs (should not arise in valid SSA, but\n   the original code preserved them so we do too).\n\nVerification:\n  lake build                       clean\n  lake exe svparser-test           34/34 (includes Test 21 pcpi_mul)\n  lake exe sim-runner-test         27/27\n  lake exe cdc-multi-clock-test    PASS",
          "timestamp": "2026-04-08T23:56:20+09:00",
          "tree_id": "dc45e1cee56cb09b4d8a0f33c5941ac1348f879b",
          "url": "https://github.com/Verilean/sparkle/commit/fae81e36e24a60c4ac3730849fca861e8439bdfd"
        },
        "date": 1775660527483,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3268429,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4150922,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4509076,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4097503,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "98ac7361c5dad230d81c0c6a091d0a9034ea75c7",
          "message": "fix(ci): make LiteX benchmark JSON bulletproof\n\nThe 'Run LiteX benchmark (10M cycles)' step was piping raw Verilator /\nbench_litex stdout through bash command substitution and interpolating\nthe values directly into a heredoc that wrote litex-bench-results.json.\nWhen either binary emitted anything non-numeric on stdout (stray\nwarnings, newlines, a nonzero exit, dlopen error messages, etc.) the\nresulting JSON became malformed and benchmark-action aborted with\n\n    Error: Output file for 'custom-(bigger|smaller)-is-better' must be\n    JSON file containing an array of entries in BenchmarkResult format\n\nChanges:\n- set -euo pipefail inside the step so silent failures are caught.\n- Capture raw stdout/stderr of both benchmarks, echo them to the log\n  for post-mortem diagnostics, then sanitize with 'tail -n1 | tr -cd 0-9'\n  to keep only the trailing numeric result.\n- Fall back to 0 when either value is empty (instead of leaving the\n  shell variable unset, which would produce a JSON syntax error).\n- Harden bench_litex.cpp: null-check dlopen/dlsym before use so we\n  get a clear error message on stderr rather than a segfault.\n- Write the JSON via 'python3 - <<PYEOF | json.dumps' rather than a\n  bash heredoc containing literal braces. This eliminates the whole\n  class of shell-quoting bugs and gives deterministic formatting.\n- Add a post-write python3 validator that parses the JSON, checks\n  it's a non-empty list of {name, unit, value} dicts with numeric\n  values, and fails loudly if not — so we never hand a half-broken\n  file to benchmark-action again.",
          "timestamp": "2026-04-09T00:03:34+09:00",
          "tree_id": "5f1142e3171511e82c6b575de467e70a1b94f065",
          "url": "https://github.com/Verilean/sparkle/commit/98ac7361c5dad230d81c0c6a091d0a9034ea75c7"
        },
        "date": 1775660955181,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3288602,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4017724,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4380111,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4046740,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "12ee4e1f1232a39fbb5226d30f7c45baf09dbdba",
          "message": "fix(ci): harden multicore + rv32 benchmark JSON writers too\n\nThe push CI failed with a decisive error message:\n\n    Error: Output file for 'custom-(bigger|smaller)-is-better' must be\n    JSON file containing an array of entries in BenchmarkResult format:\n    Unexpected token '%', ..\"\"value\": %Warning: \"... is not valid JSON\n\nSo Verilator's 8-core Vsim binary was emitting %Warning-UNSIGNED /\n%Warning-WIDTHEXPAND diagnostics on stdout at runtime; those got\ncaptured into VLTR_8CORE via command substitution and interpolated\nliterally into multicore-bench-results.json, producing\n\n    \"value\": %Warning: ...\n\nApply the same bulletproof treatment the LiteX bench step already got:\n\n- set -euo pipefail for fast failure detection.\n- sanitize_num() helper: tail -n1 | tr -cd '0-9' + fallback to 0,\n  guaranteeing the shell variable is always a pure digit string.\n- 2>&1 capture so stderr shows up in the CI log but doesn't pollute\n  the numeric extraction.\n- dlopen/dlsym NULL-checks in bench_1core/bench_8seq/bench_8par so\n  load failures print a clear stderr message instead of segfaulting.\n- Write multicore-bench-results.json via python3 json.dumps instead\n  of a bash heredoc full of literal { } / $vars — removes the whole\n  class of shell-quoting bugs.\n- Post-write python3 validator that asserts list shape and numeric\n  'value' fields, failing the step loudly if the file is malformed\n  (instead of handing it to benchmark-action and getting a cryptic\n  truncated error message).\n\nAlso apply the same sanitize_num + python writer + validator to the\nearlier rv32-bench-results.json step so the same pattern can't bite\nit later — the old grep-based extractor was probably fine but this\nkeeps all three bench steps consistent.",
          "timestamp": "2026-04-09T00:30:36+09:00",
          "tree_id": "c7aa73af466a0460b156f6325645838adae6fcc9",
          "url": "https://github.com/Verilean/sparkle/commit/12ee4e1f1232a39fbb5226d30f7c45baf09dbdba"
        },
        "date": 1775662633898,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3840170,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4214994,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5303559,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 5102906,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "fb6d0f775a24d47031c7f229549005929c985258",
          "message": "fix(ci): bump Lean to v4.28.0 so LSpec olean matches toolchain\n\nThe push CI was aborting mid-run inside Tests/AllTests with:\n\n    uncaught exception: failed to read file\n    '.lake/packages/LSpec/.lake/build/lib/lean/LSpec.olean.server',\n    incompatible header\n\nRoot cause: LSpec's pinned commit (8e6ddb17, dated pre-bump) shipped a\nlean-toolchain file declaring v4.26.0, while our project was pinned at\nv4.28.0-rc1. When lake recursed into the LSpec package elan switched to\nv4.26.0 to build it — producing oleans tagged with the v4.26.0 header\nformat — and our project then tried to load them under v4.28.0-rc1 at\nruntime, failing the header check the first time lspecIO was invoked\n(right after the BitNet test suite finished).\n\nlake update LSpec bumps the package to dc0904293d and re-aligns its\ntoolchain to v4.28.0 (stable). Our project's lean-toolchain is updated\nto match (v4.28.0-rc1 → v4.28.0) so everything compiles and loads under\none consistent Lean version.\n\nVerified locally:\n  lake build                            clean\n  lake exe test                         exit 0 (full BitNet + YOLOv8 +\n                                                 CAVLC + H.264 + AXI4)\n  lake exe svparser-test                34/34\n  lake exe sim-runner-test              27/27\n  lake exe cdc-multi-clock-test         PASS",
          "timestamp": "2026-04-09T03:41:08+09:00",
          "tree_id": "37c5d3da0589b8a891b2eb0f5dffb134831e6c34",
          "url": "https://github.com/Verilean/sparkle/commit/fb6d0f775a24d47031c7f229549005929c985258"
        },
        "date": 1775674114690,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3278358,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4136322,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4535682,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4193191,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "642e7b54a3659285ae5b037a95f335cc0cb2d38b",
          "message": "Merge pull request #19 from Verilean/feature/sim-parallel\n\nfeat(sim): add runSim auto-dispatcher for multi-domain simulation",
          "timestamp": "2026-04-09T03:57:18+09:00",
          "tree_id": "37c5d3da0589b8a891b2eb0f5dffb134831e6c34",
          "url": "https://github.com/Verilean/sparkle/commit/642e7b54a3659285ae5b037a95f335cc0cb2d38b"
        },
        "date": 1775674922350,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3278497,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4148940,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4531274,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4183672,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "74b2b8638cbb54e96555e315dd2df6a43138c513",
          "message": "feat(sim): add endpointCycles for asymmetric CDC + fix Tutorial\n\nThe CDC example in Tutorial.md Step 6 was misleading: both 'producer'\nand 'consumer' modules wrote 'input clk' and the call site passed a\nsingle uniform 'cycles := 1_000_000', making it look like the two\nendpoints shared a clock. They don't — runSim runs each endpoint on\nits own thread with its own independent evalTick loop — but the\nexample provided no way to express a frequency ratio either.\n\nWorse, the runSim refactor that introduced the typed API had silently\nregressed the original JIT.runCDC functionality: runCDC accepted two\ndistinct cycle budgets (cyclesA, cyclesB) which let callers model e.g.\na 2:1 clock ratio, but my runSim wrapper passed the same 'cycles' value\nto both sides, flattening every CDC sim to a 1:1 ratio. Tests/CDC/\nMultiClockTest had quietly inherited this by switching from 200k/100k\nto 200k/200k when I ported it.\n\nChanges:\n\n- Sparkle/Core/SimParallel.lean: runSim gains an optional\n  'endpointCycles : List UInt64 := []' parameter. When non-empty it\n  must have the same length as endpoints, and each entry becomes that\n  endpoint's cycle budget (overriding the uniform 'cycles'). When\n  empty the old behaviour is preserved. runSingleSim and\n  runMultiDomainSim are unchanged.\n\n- Tests/CDC/MultiClockTest.lean: restore the historical 200k / 100k\n  asymmetry with endpointCycles := [200000, 100000]. The CDC queue now\n  genuinely exercises the 2:1 ratio again (81k sent, 80k received vs\n  the symmetric 100k/100k).\n\n- Tests/Sim/SimRunnerTest.lean: three new regression tests (now 30/30):\n  F1 asymmetric endpointCycles [200k,100k] delivers messages\n  F2 length mismatch between endpoints and endpointCycles is rejected\n  F3 endpointCycles overrides 'cycles' when both are given\n\n- docs/Tutorial.md: rewrote the CDC section. Renamed the example\n  modules to producer_mod / consumer_mod, introduced endpointCycles\n  with an explicit 200 MHz / 100 MHz cycle ratio, and added a plain-\n  language warning that writing 'input clk' in two sim! modules does\n  NOT by itself create two domains — the two-domain-ness comes from\n  runSim running each endpoint on its own thread plus the SPSC queue\n  that CDC-synchronizes the payload. Users who need a hard 2-flop\n  synchronizer still have to add it in their Verilog explicitly.\n\nVerified:\n  lake exe svparser-test           34/34\n  lake exe sim-runner-test         30/30  (+3 from F1-F3)\n  lake exe cdc-multi-clock-test    PASS   (now exercising 200k/100k)",
          "timestamp": "2026-04-09T04:15:45+09:00",
          "tree_id": "b941864ad03949d373f4a0bb76a9de417d52e765",
          "url": "https://github.com/Verilean/sparkle/commit/74b2b8638cbb54e96555e315dd2df6a43138c513"
        },
        "date": 1775676051928,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3272711,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4138782,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4520556,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4195036,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "96c7ade9e7c9c2db4739e9142459185f92a96a4c",
          "message": "Merge pull request #20 from Verilean/feature/sim-parallel\n\nfeat(sim): add endpointCycles for asymmetric CDC + fix Tutorial",
          "timestamp": "2026-04-09T04:17:40+09:00",
          "tree_id": "b941864ad03949d373f4a0bb76a9de417d52e765",
          "url": "https://github.com/Verilean/sparkle/commit/96c7ade9e7c9c2db4739e9142459185f92a96a4c"
        },
        "date": 1775676136652,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3834830,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4214347,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5269074,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 5072845,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "ac50cf32b82af6fcb7714343de745424f6e92766",
          "message": "fix: CppSim wide integer (>64bit) support in evalTick and slice/concat\n\nTwo fixes for std::array<uint32_t, N> handling in CppSim:\n\n1. evalTick wire localization: wires >64 bits were excluded from\n   evalTick's local declarations (isScalar check), causing\n   \"undeclared identifier\" errors when evalTick referenced them.\n   Fix: declare wide integer locals with std::array zero-init.\n\n2. slice on wide integers: >> operator doesn't work on std::array.\n   Fix: emit word-level array indexing (array[wordIdx] >> bitOffset)\n   for source widths >64 bits, handling cross-word boundary cases.\n\n3. concat producing >64 bits: shift+OR chain doesn't work for\n   std::array results. Fix: emit std::array initializer with\n   word-level packing.\n\nFixes oracle-accuracy-test which exercises the SoC with BitNet\nperipheral using 80-bit intermediates (48×32 scale multiply via\nsignExtendSignal).\n\nAll tests pass: 34/34 parser, 30/30 sim-runner, 4/4 oracle-accuracy,\n3/3 BitNet SoC, 3/3 TimeMux, 7/7 golden compare, FFN golden.",
          "timestamp": "2026-04-11T09:03:47+09:00",
          "tree_id": "9342988b570d851d1e422d8021f4638f7ae1c775",
          "url": "https://github.com/Verilean/sparkle/commit/ac50cf32b82af6fcb7714343de745424f6e92766"
        },
        "date": 1775866142601,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 2937455,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4126329,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4518290,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4170346,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "a84111bc5db1b691b16a1a4b0f0fd083c4356211",
          "message": "fix: update TestLayers for rmsNormSignal and ffnBlockSignal signature changes\n\nrmsNormSignal now takes recipN : BitVec 32 parameter (Nat.pow doesn't\nreduce through synthesis). ffnBlockSignal takes explicit residualInput\nparameter (Array.getD generates unsynthesizable ite).\n\nAll tests pass including lake exe test.",
          "timestamp": "2026-04-11T09:20:12+09:00",
          "tree_id": "e8c666154ccd6711e7f4b6c4112c0fb5b471bfc6",
          "url": "https://github.com/Verilean/sparkle/commit/a84111bc5db1b691b16a1a4b0f0fd083c4356211"
        },
        "date": 1775867268773,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3518375,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4775527,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5134347,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4970219,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "b1fcbd602aa6dc44ebb64886d3fbce3a056011bf",
          "message": "fix: CppSim wide integer evalTick locals + structural test update\n\nCppSim: wide integer (>64 bit) wires declared in evalTick without\nzero-initialization (just type declaration). Avoids both the\nundeclared variable error and the per-cycle init performance hit.\nWires are always written before read (Verilog wire semantics).\n\nBitNetSoCTest: structural check updated from _gen_bitnetOut (old\nplaceholder wire name) to _gen_gateAcc + sext_msb (FFN pipeline\nindicators that survive inlining). The real BitNet FFN is now\nfully inlined into the SoC, so the old wrapper wire name is gone.\n\nAll tests pass: oracle-accuracy 4/4, BitNet SoC 3/3, parser 34/34,\nsim-runner 30/30.",
          "timestamp": "2026-04-11T09:50:30+09:00",
          "tree_id": "84774db419418400b9f173eaccf0a4062d1a839a",
          "url": "https://github.com/Verilean/sparkle/commit/b1fcbd602aa6dc44ebb64886d3fbce3a056011bf"
        },
        "date": 1775870076993,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3405817,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4618721,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5031352,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4758557,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "ed32cb5ae26562810d4b7ee689c9c002799c6c6b",
          "message": "fix: update BitNet MMIO test expected value in firmware\n\nTest 9 (BitNet MMIO) expected 0xDEADBEEF from AI_OUTPUT, which was\nthe old placeholder value. Now bitNetPeripheral runs the real FFN\npipeline, so bitNetPeripheral(0) = 0. Updated expected value to 0.\n\nRebuilt firmware.hex with riscv32-none-elf-gcc.\nCppSim: ALL TESTS PASSED (including Test 9 BitNet MMIO).",
          "timestamp": "2026-04-11T11:25:27+09:00",
          "tree_id": "2dd432ea40b1de137eea99bb37b4526bf4f3e250",
          "url": "https://github.com/Verilean/sparkle/commit/ed32cb5ae26562810d4b7ee689c9c002799c6c6b"
        },
        "date": 1775874677666,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3132687,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4127003,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4309060,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4042885,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "0a6400738936eb1f6f4931958e28f395bc04554a",
          "message": "Merge pull request #21 from Verilean/feature/fpga\n\nAdd Equivalence Verification Checking and SoC with Bitnet",
          "timestamp": "2026-04-11T12:22:35+09:00",
          "tree_id": "2dd432ea40b1de137eea99bb37b4526bf4f3e250",
          "url": "https://github.com/Verilean/sparkle/commit/0a6400738936eb1f6f4931958e28f395bc04554a"
        },
        "date": 1775878037991,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3100598,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4128759,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4500543,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4136387,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "f3af4e38661e152661c704c4bf9f990a542b8bd3",
          "message": "test: top-level integration sim — pipeline starts correctly\n\nTopLevelSim.lean drives the full BitNet accelerator through HostIF:\n  cycle 2: write TOKEN_IN = 0x10000\n  cycle 3: write CTRL.go = 1\n  cycle 4+: observe status\n\nResults (50 cycles):\n  ✅ busy=true after go pulse (accelerator started)\n  ✅ perfCycles counting (performance counter active)\n  ✅ STATUS=0x2 (busy bit set)\n  ✅ No crash (all 50 cycles complete)\n  ⚠ done not asserted (expected: zero weights + no HBM response\n     means forward pass cannot complete)\n\nThis proves the top-level wiring is correct: HostIF register writes\npropagate through AutoRegressive → FullModel, and the FSM enters\nthe expected busy state. Full completion requires weight data from\nHBM (or a simulation model providing valid responses).",
          "timestamp": "2026-04-11T20:36:09+09:00",
          "tree_id": "2c6c8c58822980c49eb476abb49347b863805f7f",
          "url": "https://github.com/Verilean/sparkle/commit/f3af4e38661e152661c704c4bf9f990a542b8bd3"
        },
        "date": 1775908703595,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3108619,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4116526,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4470530,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4108105,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "f9dc9ba819940dcf58c58be55d103e40b7d8a28c",
          "message": "Merge pull request #22 from Verilean/feature/fpga\n\nUpdate the FPGA implementation",
          "timestamp": "2026-04-11T22:39:12+09:00",
          "tree_id": "2c6c8c58822980c49eb476abb49347b863805f7f",
          "url": "https://github.com/Verilean/sparkle/commit/f9dc9ba819940dcf58c58be55d103e40b7d8a28c"
        },
        "date": 1775915019865,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3505824,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4794465,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5313532,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 5108999,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "4dd22e917045193905bc1a073ce25f535f09d2f9",
          "message": "feat: position/velocity/altitude control + spray mission simulation\n\nAdd the missing navigation stack between path planner and attitude PID:\n  - PositionController.lean: position P → velocity PID → attitude setpoint\n  - Altitude PID → throttle command\n  - SprayDroneSoCParallel: full pipeline wired (planner → nav → attitude → motors)\n\nClosed-loop simulation validates 4 capabilities:\n  1. Hover stability: altitude holds at 3.000m (±0.001m)\n  2. Altitude control: climbs from 0→3m, settles within 5s\n  3. Waypoint tracking: reaches 7.5m/10m target in 10s\n  4. Spray mission: 3-pass serpentine over 50m field\n     - 64m total distance, 1 waypoint hit\n     - Max attitude: roll=0.033 rad, pitch=0.034 rad\n     - Altitude error: 0.0006m (sub-millimeter hold)\n     - Spray active during flight legs\n\nRegressions: 34/34 parser, 30/30 sim-runner.",
          "timestamp": "2026-04-12T18:23:40+09:00",
          "tree_id": "607e197de3098b50a8bc9fa7c6c28b745a1fd444",
          "url": "https://github.com/Verilean/sparkle/commit/4dd22e917045193905bc1a073ce25f535f09d2f9"
        },
        "date": 1776049251517,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3118750,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4106399,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4514576,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4158595,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "fb1e464b5381830a7de792f3f9e80613dae8a05f",
          "message": "Merge pull request #23 from Verilean/feature/fpga\n\nAdd the drone SoC",
          "timestamp": "2026-04-13T11:58:18+09:00",
          "tree_id": "607e197de3098b50a8bc9fa7c6c28b745a1fd444",
          "url": "https://github.com/Verilean/sparkle/commit/fb1e464b5381830a7de792f3f9e80613dae8a05f"
        },
        "date": 1776049380526,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3110755,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4120527,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4495059,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4120267,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "599c8125c368bffd3646c516366a9087d0b89519",
          "message": "Merge pull request #25 from Verilean/fix/tutorial\n\nFix documents to test the codes in Tutorial",
          "timestamp": "2026-04-18T14:53:18+09:00",
          "tree_id": "302335bd11e124786db88ee2d4a7442eae56b092",
          "url": "https://github.com/Verilean/sparkle/commit/599c8125c368bffd3646c516366a9087d0b89519"
        },
        "date": 1776491902297,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3111247,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4124375,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4392324,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4114344,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "252341078dba3c2612719746e6a459dada2248ea",
          "message": "Merge pull request #26 from xiangze/howtouse\n\nadd How to import and use external project",
          "timestamp": "2026-04-25T04:23:32+09:00",
          "tree_id": "45b6373675b2204947fb0686cab378fb02540d76",
          "url": "https://github.com/Verilean/sparkle/commit/252341078dba3c2612719746e6a459dada2248ea"
        },
        "date": 1777058889923,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3134537,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4123858,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4500137,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4114682,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "2aea0922ae984f1b16af2e9a17ef7d97b9a79c62",
          "message": "Merge pull request #29 from Verilean/fix/tutorial\n\nAdd proofs for RV32",
          "timestamp": "2026-05-05T16:44:11+09:00",
          "tree_id": "d9c500480127c25a7f1ea554471eccddbb8116dd",
          "url": "https://github.com/Verilean/sparkle/commit/2aea0922ae984f1b16af2e9a17ef7d97b9a79c62"
        },
        "date": 1777967376849,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3656415,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3652085,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4322575,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4187965,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "634d55b13042e15f2b296031bfb9156c17d47e74",
          "message": "declare_signal_state: generate Name.mk named-field constructor\n\nAdds a record-style constructor `Name.mk` to the\n`declare_signal_state` macro. For an n-field state declared as\n\n    declare_signal_state CounterParityOut\n      | count  : BitVec 8 := 0#8\n      | parity : Bool     := false\n\nthe macro now also emits\n\n    def CounterParityOut.mk {dom : DomainConfig}\n      : (count : Signal dom (BitVec 8)) →\n        (parity : Signal dom Bool) →\n        Signal dom CounterParityOut :=\n      fun count parity => bundle2 count parity\n\nso callers can build the output side by field name, mirroring how\nthey read it:\n\n    -- read by field name\n    let count := CounterParityOut.count self\n\n    -- write by field name (NEW)\n    CounterParityOut.mk (count := countOut) (parity := parityOut)\n\nBundle order comes from the macro, not from the call site, so a\nfield reorder in `declare_signal_state` cannot silently swap the\noutput data — Lean's named-argument resolution catches it.\n\nUpdates:\n\n  - `Sparkle/Core/StateMacro.lean`: append step 7 to the\n    macro's elaboration that emits `Name.mk` via a typed\n    function abstraction (no bracketedBinder syntax tricks).\n  - `tutorial-extended/TutorialExtended/Step2_MultipleOutputs.lean`:\n    add a 4th variant `counterAndParity_record_mk` demonstrating\n    the new pattern. The runDemo prints all 4 traces; they match.\n  - `tutorial-extended/TutorialExtended/Step2_VerilogDump.lean`:\n    `#synthesizeVerilog` the new variant; confirms the same\n    `_gen_countOut`/`_gen_parityOut` wires are produced.\n  - `docs/Tutorial_Extended.md`: new \"(d)\" section, updated\n    summary table.\n\nVerified:\n  - Full project build clean (64 jobs)\n  - All existing `declare_signal_state` invocations across\n    IP/RV32, IP/Bus, IP/Video, IP/YOLOv8, etc. continue to compile\n  - tutorial-extended-run prints identical traces for variants\n    (a), (b), (c), (d)\n  - Verilog output for (c) and (d) is structurally identical\n    (same wire names, same always_ff blocks, same bundle assign)",
          "timestamp": "2026-05-05T17:11:56+09:00",
          "tree_id": "f3320b83c4838e6ed3f5412134a5d242f492384d",
          "url": "https://github.com/Verilean/sparkle/commit/634d55b13042e15f2b296031bfb9156c17d47e74"
        },
        "date": 1777969273638,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3119931,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3321856,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 3671716,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 3423017,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "32f41e332ed170e21247ce1f6f8241aabad9e285",
          "message": "Tutorial.md: introduce declare_signal_state and Name.mk in Step 1\n\nAdd a \"Multi-output modules and declare_signal_state\" subsection\nright after the single-counter example, demonstrating:\n\n  - declare_signal_state field-list syntax\n  - read-by-name (CounterParityOut.count self)\n  - write-by-name (CounterParityOut.mk (count := ...) (parity := ...))\n  - the auto-generated default / wireNames / fromWires helpers\n\nA concrete `counterAndParity` example mirrors the anonymous-tuple\npattern but uses the record + Name.mk variant directly. Caller\nside also uses field-name accessors.\n\nForward-links to docs/Tutorial_Extended.md for the full\nwalkthrough (anonymous tuple → let-named → record + bundleAll!\n→ record + Name.mk) with trade-offs of each.\n\nBridges the gap between Tutorial.md's single-counter intro and\nTutorial_Extended.md's deeper module-composition material:\nreaders learn the named-record I/O pattern as soon as they need\nmore than one output, without having to hunt for the right\nchapter.",
          "timestamp": "2026-05-05T17:20:36+09:00",
          "tree_id": "6d05573aace61658debcc604969319048e3ff2e9",
          "url": "https://github.com/Verilean/sparkle/commit/32f41e332ed170e21247ce1f6f8241aabad9e285"
        },
        "date": 1777970001434,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3129351,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3317552,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 3646136,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 3405210,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "e46ab57c8e2b76a40020de57074666e1c58bb3f7",
          "message": "Merge pull request #30 from Verilean/feature/named-outputs\n\ndeclare_signal_state: generate Name.mk named-field constructor",
          "timestamp": "2026-05-05T17:35:27+09:00",
          "tree_id": "79db2a2a501c5a31266cfea81b5d641c4ccec2c5",
          "url": "https://github.com/Verilean/sparkle/commit/e46ab57c8e2b76a40020de57074666e1c58bb3f7"
        },
        "date": 1777970441595,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 4684445,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4699458,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5604323,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 5459887,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "a34600b42b0ee4288268a956e9245ecac6c305ce",
          "message": "Tutorial.md: introduce Signal.circuit do imperative HW DSL\n\nAdd a \"Imperative-style hardware: Signal.circuit do\" subsection\nright after the named-record I/O introduction in Step 1, with:\n\n  - Syntax overview (let x ← Signal.reg init, x <~ rhs, let y :=\n    rhs, return expr)\n  - Counter rewrite — same circuit as the canonical Step 1 example\n  - 3-stage shift pipeline as a multi-register example\n  - Note on when NOT to use it (need multiple named outputs →\n    Name.mk + Signal.loop is more flexible; Signal.circuit do\n    returns a single Signal)\n  - Forward link to the runnable example file\n\nNew runnable example:\n\n  - tutorial-extended/TutorialExtended/Step8_CircuitDoNotation.lean —\n    four worked examples (counter / up-down / 3-stage shift /\n    enabled counter) demonstrating both registered-state assignment\n    (`<~`) and combinational `let` bindings in the same do block.\n  - tutorial-extended/TutorialExtended/Run.lean — extended to\n    invoke Step 8's runDemo, which prints the four traces and\n    confirms (a) the counter increments, (b) up/down respects en,\n    (c) 3-stage shift introduces 3-cycle latency (input 0xAA at\n    cycle 1 emerges at cycle 4), (d) enabled counter only ticks\n    on the cycles when en is true.\n\nThe macro desugars to Signal.loop + Signal.register + bundleAll!\nover the next-state expressions, so synthesis output, JIT codegen,\nand Signal.atTime evaluation are identical to the hand-written\nversion. Verified by `lake build` (64 jobs clean) and\n`lake exe tutorial-extended-run` (Step 8 traces match expected\noutput).",
          "timestamp": "2026-05-05T17:33:02+09:00",
          "tree_id": "79db2a2a501c5a31266cfea81b5d641c4ccec2c5",
          "url": "https://github.com/Verilean/sparkle/commit/a34600b42b0ee4288268a956e9245ecac6c305ce"
        },
        "date": 1777970455094,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3662057,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3683953,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4436700,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4314410,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "ee8a7e9081c12eac0653578ca4ea30d40cd70e0c",
          "message": "Add .claude/ to .gitignore (Claude Code working dir)\n\nRemoves the accidentally-committed `.claude/scheduled_tasks.lock`\nand prevents future commits from picking up Claude Code's\nlocal working state.",
          "timestamp": "2026-05-08T13:43:54+09:00",
          "tree_id": "a6ae3cae493812d83f165c9bd90b970a376a48bd",
          "url": "https://github.com/Verilean/sparkle/commit/ee8a7e9081c12eac0653578ca4ea30d40cd70e0c"
        },
        "date": 1778216410038,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 2332684,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3655438,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4287887,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4227296,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "6e9fd99fd9261e19fd53ddabdd6bb87710a78f79",
          "message": "Merge pull request #31 from xiangze/FPU\n\nFPU with proofs",
          "timestamp": "2026-05-09T13:47:58+09:00",
          "tree_id": "31fb81df206f8438dc1464858a7508d1ea73ad23",
          "url": "https://github.com/Verilean/sparkle/commit/6e9fd99fd9261e19fd53ddabdd6bb87710a78f79"
        },
        "date": 1778302430752,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3127636,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3251219,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 3625137,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 3429029,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "41333d2b8fc6d756fcaffd1b939f7b30c8ea4a5c",
          "message": "Merge pull request #27 from xiangze/slice_operator_comma\n\ndefine and prove bit slice operatror v[hi,lo]",
          "timestamp": "2026-05-09T13:50:20+09:00",
          "tree_id": "07dc69b7ca76c85c3666b2b168667f186b756c19",
          "url": "https://github.com/Verilean/sparkle/commit/41333d2b8fc6d756fcaffd1b939f7b30c8ea4a5c"
        },
        "date": 1778302573994,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3122855,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3267562,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 3672698,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 3448137,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "9d1cb48c28dc2d658f05017c02290165daf85702",
          "message": ".dockerignore: refresh comments to match the current Dockerfile\n\nThe header explained the file as protection against a blanket\n`COPY . /workspace/sparkle` that the tutorial Dockerfile used\nto do.  That `COPY .` was replaced months ago with a hand-picked\nlist of directories (`Sparkle/`, `c_src/`, `lakefile.toml`,\ndocs/tutorial/, tutorial-extended/, …), so the entries below\nare now defence-in-depth rather than load-bearing.\n\nJust rewrite the comment block to say so; no entries\nadded/removed.",
          "timestamp": "2026-05-12T06:33:50+09:00",
          "tree_id": "ae97298253e9c8e925c12f31c04fd632972bbcef",
          "url": "https://github.com/Verilean/sparkle/commit/9d1cb48c28dc2d658f05017c02290165daf85702"
        },
        "date": 1778536938467,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 2874729,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3301991,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 3674235,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 3464307,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "670c8de6e3ba3759f8d42e2d3746a46eeca4a302",
          "message": ".dockerignore: refresh comments to match the current Dockerfile\n\nThe header explained the file as protection against a blanket\n`COPY . /workspace/sparkle` that the tutorial Dockerfile used\nto do.  That `COPY .` was replaced months ago with a hand-picked\nlist of directories (`Sparkle/`, `c_src/`, `lakefile.toml`,\ndocs/tutorial/, tutorial-extended/, …), so the entries below\nare now defence-in-depth rather than load-bearing.\n\nJust rewrite the comment block to say so; no entries\nadded/removed.",
          "timestamp": "2026-05-12T08:34:00+09:00",
          "tree_id": "82445a88dadf1b6ddac84c68315596821b552612",
          "url": "https://github.com/Verilean/sparkle/commit/670c8de6e3ba3759f8d42e2d3746a46eeca4a302"
        },
        "date": 1778542819974,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3646425,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3644293,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4348958,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4244690,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "1d51cb0d20de0a7bc8a573f4b30bd975371ede4e",
          "message": "Merge pull request #32 from Verilean/feature/notebook\n\nFeature/notebook",
          "timestamp": "2026-05-12T09:02:08+09:00",
          "tree_id": "4984953fc994bbcd491ac3da12d9dbcc91774301",
          "url": "https://github.com/Verilean/sparkle/commit/1d51cb0d20de0a7bc8a573f4b30bd975371ede4e"
        },
        "date": 1778544467486,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3137539,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3201177,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 3641096,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 3424884,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "d9fb8bcf670839a0206ef7fd6d5d6394fcd133a2",
          "message": ".github/workflows/docker-image.yml: lowercase the ghcr.io owner\n\n`${{ github.repository_owner }}` returns the org's display\ncase (\"Verilean\"), but ghcr.io rejects tags whose repository\nname has any uppercase characters:\n\n    ERROR: failed to build: invalid tag\n      \"ghcr.io/Verilean/sparkle-tutorial:latest\":\n      repository name must be lowercase\n\nResolve it in the existing \"Resolve image tag\" step via\nbash's `${VAR,,}` lowercasing on `$GITHUB_REPOSITORY_OWNER`,\nexpose as `steps.tag.outputs.owner`, and reference that from\nthe build/push step's tags list.",
          "timestamp": "2026-05-12T11:20:04+09:00",
          "tree_id": "a1fc1d5735dc04b7bb8f13fccd04390cab700bea",
          "url": "https://github.com/Verilean/sparkle/commit/d9fb8bcf670839a0206ef7fd6d5d6394fcd133a2"
        },
        "date": 1778552800516,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3114931,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3236030,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 3638722,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 3406157,
            "unit": "cycles/sec"
          }
        ]
      }
    ]
  }
}