window.BENCHMARK_DATA = {
  "lastUpdate": 1775655549446,
  "repoUrl": "https://github.com/Verilean/sparkle",
  "entries": {
    "RV32 SoC Simulation Benchmark (Verilator vs JIT)": [
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "013443ba59c63ef7a13f40270d2db4230cbb4a0e",
          "message": "ci: preserve benchmark JSON across git stash",
          "timestamp": "2026-03-26T12:24:42+09:00",
          "tree_id": "2c4e9dd57e4df348ac816af39b6d0bb5e2192a7f",
          "url": "https://github.com/Verilean/sparkle/commit/013443ba59c63ef7a13f40270d2db4230cbb4a0e"
        },
        "date": 1774495789741,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3285506,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4856146,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5465489,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4968426,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junjihashimoto@users.noreply.github.com",
            "name": "junji hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "e1c53641a220e3c602c86ab73517f8ed8ea92f93",
          "message": "Merge pull request #14 from Verilean/feature/rv32\n\nci: preserve benchmark JSON across git stash",
          "timestamp": "2026-03-26T12:25:40+09:00",
          "tree_id": "2c4e9dd57e4df348ac816af39b6d0bb5e2192a7f",
          "url": "https://github.com/Verilean/sparkle/commit/e1c53641a220e3c602c86ab73517f8ed8ea92f93"
        },
        "date": 1774495849619,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3280838,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4946544,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5469307,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4978734,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "53a9286586ccf563348df73fe880d1ef03168d06",
          "message": "chore: gitignore verilator/generated_soc_cppsim.h build artifact\n\nCompanion to the already-ignored generated_soc_jit.cpp. Both files are\nregenerated by 'lake build IP.RV32.SoCVerilog'.",
          "timestamp": "2026-04-08T21:37:07+09:00",
          "tree_id": "6ae8e82310e17eae00d05dd6634a5eeda1dc362b",
          "url": "https://github.com/Verilean/sparkle/commit/53a9286586ccf563348df73fe880d1ef03168d06"
        },
        "date": 1775652117939,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3829037,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 3812284,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 5145965,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4928097,
            "unit": "cycles/sec"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "committer": {
            "email": "junji.hashimoto@gree.net",
            "name": "Junji Hashimoto",
            "username": "junjihashimoto"
          },
          "distinct": true,
          "id": "cd9d63c2b01a6e7249288598dc50548bbd292ace",
          "message": "fix(CppSim): dedupe statement declarations by identifier\n\nLiteX-style Verilog patterns like\n\n    reg [9:0] storage_1_dat0;\n    always @(posedge clk)\n        storage_1_dat0 <= storage_1[addr];\n\nsurface in the IR as both a `.memory` read-data port and a standalone\n`.register` statement with the same name. emitModule then emitted two\nclass member declarations for the same identifier (different types,\nbecause the register path falls back to 32-bit when the name is missing\nfrom typeMap), producing invalid C++:\n\n    uint16_t storage_1_dat0;  // from memory\n    uint32_t storage_1_dat0;  // from register ← redeclaration error\n\nFix: after collecting `stmtDecls` from all statement emissions, dedupe\nby extracting the trailing identifier token and keeping the first\noccurrence. Memory read-data ports are emitted before the register\nfallback and already carry the correct dataWidth, so keeping the first\ncopy is the right choice.\n\nThis unblocks the LiteX JIT build in GitHub Actions (the CI step that\ncompiles /tmp/litex_jit.cpp was failing with\n'redeclaration of storage_1_dat0').",
          "timestamp": "2026-04-08T21:53:38+09:00",
          "tree_id": "6fec48d398a43ee54d1b8c7082704eb5ecd1b626",
          "url": "https://github.com/Verilean/sparkle/commit/cd9d63c2b01a6e7249288598dc50548bbd292ace"
        },
        "date": 1775655549066,
        "tool": "customBiggerIsBetter",
        "benches": [
          {
            "name": "Verilator (10M cycles)",
            "value": 3301683,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT eval+tick (10M cycles)",
            "value": 4015768,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick fused (10M cycles)",
            "value": 4454551,
            "unit": "cycles/sec"
          },
          {
            "name": "JIT evalTick+6wires (10M cycles)",
            "value": 4165818,
            "unit": "cycles/sec"
          }
        ]
      }
    ]
  }
}