/-
  SvWrapper — give a Sparkle design the port list a SystemVerilog user
  expects.

  Sparkle names a module's inputs after the Lean binders (`_gen_inData`)
  and packs a tuple result into one `out` vector.  A design that is to be
  instantiated from somebody else's SystemVerilog — or bound by prefix by a
  verification component (`s_axis_tdata`, `m_axis_tvalid`, …) — needs the
  conventional names, and often the conventional reset (`aresetn`, active
  low).  `emit` writes the thin module that does the renaming:

    module axis_scale (input logic clk, input logic rst,
                       input logic [31:0] s_axis_tdata, …,
                       output logic [31:0] m_axis_tdata, …);
      logic [38:0] out;
      Sparkle_…_axisScale u (.clk(clk), .rst(rst), ._gen_inData(s_axis_tdata), …, .out(out));
      assign m_axis_tdata = out[31:0];
      …
    endmodule

  No logic is added: every output is a slice of (or an expression over) the
  inner module's outputs.
-/

namespace Sparkle.Backend.SvWrapper

structure Wrapper where
  /-- name of the module to write -/
  name : String
  /-- the Sparkle module it wraps (the name in the emitted Verilog) -/
  inner : String
  /-- the wrapper's clock and reset ports -/
  clock : String := "clk"
  reset : String := "rst"
  /-- `false`: the wrapper's reset is active low (it is inverted for Sparkle) -/
  resetActiveHigh : Bool := true
  /-- the inner module's output ports -/
  innerOutputs : List (String × Nat)
  /-- (port, width, inner input port it drives) -/
  inputs : List (String × Nat × String)
  /-- (port, width, SystemVerilog expression over the inner outputs) -/
  outputs : List (String × Nat × String)

private def range (w : Nat) : String := if w ≤ 1 then "" else s!"[{w - 1}:0] "

def emit (w : Wrapper) : String :=
  let ports :=
    [s!"    input  logic {w.clock}", s!"    input  logic {w.reset}"]
    ++ w.inputs.map (fun (n, wd, _) => s!"    input  logic {range wd}{n}")
    ++ w.outputs.map (fun (n, wd, _) => s!"    output logic {range wd}{n}")
  let conns :=
    [s!".clk({w.clock})", s!".rst({if w.resetActiveHigh then w.reset else "!" ++ w.reset})"]
    ++ w.inputs.map (fun (n, _, inner) => s!".{inner}({n})")
    ++ w.innerOutputs.map (fun (n, _) => s!".{n}({n}_w)")
  String.intercalate "\n" <|
    [ s!"// Generated by Sparkle HDL — port-name wrapper around {w.inner}"
    , s!"module {w.name} ("
    , String.intercalate ",\n" ports
    , ");" ]
    ++ w.innerOutputs.map (fun (n, wd) => s!"    logic {range wd}{n}_w;")
    ++ [ s!"    {w.inner} u ({String.intercalate ", " conns});" ]
    ++ w.outputs.map (fun (n, _, e) => s!"    assign {n} = {e};")
    ++ [ "endmodule", "" ]

end Sparkle.Backend.SvWrapper
