/-
  Weight-stationary systolic array: matrix–vector product y = Wᵀ·a.

  R × C processing elements.  PE (i, j) holds the constant int8 weight
  W[i][j].  Each clock it registers the int8 activation arriving from the
  left (passing it on to the right) and adds `activation × weight` to the
  partial sum arriving from above (passing the sum down):

      a_i ─▶ PE(i,0) ─▶ PE(i,1) ─▶ …          aOut' = aIn
               │          │                    pOut' = pIn + aIn · W[i][j]
               ▼          ▼
            PE(i+1,0)  PE(i+1,1)

  With the activations held, the bottom row settles to
  y_j = Σ_i a_i · W[i][j] after R + C cycles.

  The array is one `@[hardware_module]` instance per PE, generated by
  `systolic_grid%`, so the GPU intra backend (`#writeCudaIntraDesign`)
  simulates it with one thread per PE.  Activations enter as one packed
  vector (8 bits per row), results leave as one packed vector (32 bits per
  column).
-/
import Sparkle
import Sparkle.Compiler.Elab

namespace Sparkle.IP.Systolic

open Sparkle.Core.Domain
open Sparkle.Core.Signal

structure PeOut (dom : DomainConfig) where
  /-- the activation, one cycle later (to the right-hand neighbour) -/
  aOut : Signal dom (BitVec 8)
  /-- the partial sum (to the neighbour below) -/
  pOut : Signal dom (BitVec 32)

instance {dom : DomainConfig} : Sparkle.Core.HasDomain (PeOut dom) dom := ⟨⟩

/-- One multiply-accumulate cell.  Both outputs are registers, so the cell
    is Moore: its outputs depend on its state only. -/
@[hardware_module] def pe {dom : DomainConfig}
    (aIn : Signal dom (BitVec 8)) (pIn : Signal dom (BitVec 32))
    (w : Signal dom (BitVec 8)) : PeOut dom :=
  circuit do
    let aReg ← Signal.reg (0#8)
    let pReg ← Signal.reg (0#32)
    let aS := (aReg : Signal dom (BitVec 8))
    let pS := (pReg : Signal dom (BitVec 32))
    let prod := aIn.map (BitVec.signExtend 32 ·) * w.map (BitVec.signExtend 32 ·)
    aReg <~ aIn
    pReg <~ pIn + prod
    return ({ aOut := aS, pOut := pS } : PeOut dom)

/-- The weight matrix: a fixed pattern of int8 values in −2..2. -/
def weightInt (i j : Nat) : Int := Int.ofNat ((i * 7 + j * 3) % 5) - 2

/-- `weightInt` as the 8-bit constant the PE takes (two's complement). -/
def weight (i j : Nat) : BitVec 8 := BitVec.ofNat 8 (((i * 7 + j * 3) % 5 + 254) % 256)

/-- Row `i`'s activation: bits `[8i+7 : 8i]` of the packed input. -/
def activation {dom : DomainConfig} {n : Nat}
    (a : Signal dom (BitVec n)) (i : Nat) : Signal dom (BitVec 8) :=
  a.map (BitVec.extractLsb' (8 * i) 8 ·)

/-- 4 × 4: 16 PEs. -/
def matVec4 {dom : DomainConfig} (a : Signal dom (BitVec 32)) : Signal dom (BitVec 128) :=
  systolic_grid% 4 4
    (cell i j left up => pe left up (Signal.pure (weight i j)))
    (right := aOut) (down := pOut)
    (leftEdge i => activation a i)
    (topEdge j => Signal.pure 0#32)

/-- 16 × 16: 256 PEs. -/
def matVec16 {dom : DomainConfig} (a : Signal dom (BitVec 128)) : Signal dom (BitVec 512) :=
  systolic_grid% 16 16
    (cell i j left up => pe left up (Signal.pure (weight i j)))
    (right := aOut) (down := pOut)
    (leftEdge i => activation a i)
    (topEdge j => Signal.pure 0#32)

/-! ### Reference -/

/-- Activation `i` of a packed vector, as a signed integer. -/
def actInt {n : Nat} (a : BitVec n) (i : Nat) : Int := (a.extractLsb' (8 * i) 8).toInt

/-- y_j = Σ_i a_i · W[i][j], as the 32-bit value the array produces. -/
def matVecRef {n : Nat} (rows : Nat) (a : BitVec n) (j : Nat) : BitVec 32 :=
  BitVec.ofInt 32 ((List.range rows).foldl (fun acc i => acc + actInt a i * weightInt i j) 0)

/-- Column `j` of a packed result. -/
def column {n : Nat} (y : BitVec n) (j : Nat) : BitVec 32 := y.extractLsb' (32 * j) 32

end Sparkle.IP.Systolic
