/*
 * H.264 Quantization / Dequantization — Golden Reference Generator
 *
 * Forward quantization (H.264 spec):
 *   level = (|coeff| * MF[qp%6][pos] + f) >> qbits
 *   where qbits = 15 + floor(qp/6), f = 2^qbits / (isIntra ? 3 : 6)
 *
 * Inverse dequantization (H.264 spec):
 *   coeff' = level * V[qp%6][pos] << floor(qp/6)  (for qp >= 6*0)
 *
 * Tables from H.264 Table 8-12, 8-13.
 */

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <initializer_list>

// MF table (multiplication factor for quantization)
// Indexed by [qp%6][position_class]
// position_class: 0 = (0,0),(2,0),(0,2),(2,2)
//                 1 = other even positions
//                 2 = odd positions
static const int MF[6][3] = {
    {13107, 5243, 8066},
    {11916, 4660, 7490},
    {10082, 4194, 6554},
    { 9362, 3647, 5825},
    { 8192, 3355, 5243},
    { 7282, 2893, 4559}
};

// V table (scaling factor for dequantization)
static const int V[6][3] = {
    {10, 16, 13},
    {11, 18, 14},
    {13, 20, 16},
    {14, 23, 18},
    {16, 25, 20},
    {18, 29, 23}
};

// Position class for 4×4 block position
int pos_class(int pos) {
    int row = pos / 4;
    int col = pos % 4;
    if ((row % 2 == 0) && (col % 2 == 0)) return 0;
    if ((row % 2 == 0) || (col % 2 == 0)) return 2;  // one even, one odd
    return 1;  // both odd
}

// Forward quantization (intra)
int quant(int coeff, int qp, int pos) {
    int qp_mod6 = qp % 6;
    int qp_div6 = qp / 6;
    int qbits = 15 + qp_div6;
    int f = (1 << qbits) / 3;  // intra
    int mf = MF[qp_mod6][pos_class(pos)];

    int abs_coeff = abs(coeff);
    int level = (abs_coeff * mf + f) >> qbits;
    return (coeff >= 0) ? level : -level;
}

// Inverse dequantization
int dequant(int level, int qp, int pos) {
    int qp_mod6 = qp % 6;
    int qp_div6 = qp / 6;
    int v = V[qp_mod6][pos_class(pos)];

    return level * v * (1 << qp_div6);
}

int main() {
    printf("-- H.264 Quantization Golden Values\n");
    printf("-- Generated by generate_quant_golden.cpp\n\n");

    // Test coefficients
    int coeffs[] = {136, -28, 0, -4, -112, 0, 0, 0, 0, 0, 0, 0, -16, 0, 0, 0};

    for (int qp : {0, 10, 20, 30, 40, 51}) {
        printf("-- QP = %d\n", qp);
        printf("  -- Quantized levels:\n  #[");
        int levels[16];
        for (int i = 0; i < 16; i++) {
            levels[i] = quant(coeffs[i], qp, i);
            if (i > 0) printf(", ");
            printf("%d", levels[i]);
        }
        printf("]\n");

        printf("  -- Dequantized coefficients:\n  #[");
        for (int i = 0; i < 16; i++) {
            int dq = dequant(levels[i], qp, i);
            if (i > 0) printf(", ");
            printf("%d", dq);
        }
        printf("]\n");

        // Compute max error
        int max_err = 0;
        for (int i = 0; i < 16; i++) {
            int dq = dequant(levels[i], qp, i);
            int err = abs(dq - coeffs[i]);
            if (err > max_err) max_err = err;
        }
        printf("  -- Max quant/dequant error: %d\n\n", max_err);
    }

    // Verify zero preservation
    printf("-- Zero preservation: quant(0, qp=20, pos=0) = %d\n", quant(0, 20, 0));
    printf("-- Sign preservation: quant(5, 20, 0) = %d, quant(-5, 20, 0) = %d\n",
           quant(5, 20, 0), quant(-5, 20, 0));

    return 0;
}
