/*
 * H.264 4×4 Integer DCT / IDCT — Golden Reference Generator
 *
 * Forward transform (H.264 spec 8.5.10):
 *   Cf = [[ 1,  1,  1,  1],
 *         [ 2,  1, -1, -2],
 *         [ 1, -1, -1,  1],
 *         [ 1, -2,  2, -1]]
 *   Y = Cf * X * Cf^T (with post-scaling)
 *
 * Inverse transform (H.264 spec 8.5.12):
 *   Y = Ci^T * (X * Ci) with rounding: (result + 32) >> 6
 *
 * Prints golden values as Lean-compatible constants.
 */

#include <cstdio>
#include <cstdlib>
#include <cmath>

// Forward 4×4 integer DCT (H.264 integer transform, no post-scaling)
void forward_dct_4x4(int input[4][4], int output[4][4]) {
    int temp[4][4];

    // Row transform: Y = Cf * X
    for (int i = 0; i < 4; i++) {
        int s0 = input[i][0] + input[i][3];
        int s1 = input[i][1] + input[i][2];
        int d0 = input[i][0] - input[i][3];
        int d1 = input[i][1] - input[i][2];

        temp[i][0] = s0 + s1;
        temp[i][1] = 2 * d0 + d1;
        temp[i][2] = s0 - s1;
        temp[i][3] = d0 - 2 * d1;
    }

    // Column transform: Y = temp * Cf^T
    for (int j = 0; j < 4; j++) {
        int s0 = temp[0][j] + temp[3][j];
        int s1 = temp[1][j] + temp[2][j];
        int d0 = temp[0][j] - temp[3][j];
        int d1 = temp[1][j] - temp[2][j];

        output[0][j] = s0 + s1;
        output[1][j] = 2 * d0 + d1;
        output[2][j] = s0 - s1;
        output[3][j] = d0 - 2 * d1;
    }
}

// Inverse 4×4 integer DCT (H.264 integer inverse transform)
void inverse_dct_4x4(int input[4][4], int output[4][4]) {
    int temp[4][4];

    // Row transform: Ci * X (horizontal)
    for (int i = 0; i < 4; i++) {
        int s0 = input[i][0] + input[i][2];
        int s1 = input[i][0] - input[i][2];
        int d0 = (input[i][1] >> 1) - input[i][3];
        int d1 = input[i][1] + (input[i][3] >> 1);

        temp[i][0] = s0 + d1;
        temp[i][1] = s1 + d0;
        temp[i][2] = s1 - d0;
        temp[i][3] = s0 - d1;
    }

    // Column transform: temp * Ci^T (vertical) with rounding
    for (int j = 0; j < 4; j++) {
        int s0 = temp[0][j] + temp[2][j];
        int s1 = temp[0][j] - temp[2][j];
        int d0 = (temp[1][j] >> 1) - temp[3][j];
        int d1 = temp[1][j] + (temp[3][j] >> 1);

        output[0][j] = (s0 + d1 + 32) >> 6;
        output[1][j] = (s1 + d0 + 32) >> 6;
        output[2][j] = (s1 - d0 + 32) >> 6;
        output[3][j] = (s0 - d1 + 32) >> 6;
    }
}

void print_block(const char* name, int block[4][4]) {
    printf("  -- %s\n", name);
    printf("  #[");
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            if (i > 0 || j > 0) printf(", ");
            printf("%d", block[i][j]);
        }
    }
    printf("]\n\n");
}

int main() {
    printf("-- H.264 4×4 Integer DCT Golden Values\n");
    printf("-- Generated by generate_dct_golden.cpp\n\n");

    // Test block 1: Simple residual block
    int block1[4][4] = {
        { 1,  2,  3,  4},
        { 5,  6,  7,  8},
        { 9, 10, 11, 12},
        {13, 14, 15, 16}
    };

    int dct1[4][4], idct1[4][4];
    forward_dct_4x4(block1, dct1);
    inverse_dct_4x4(dct1, idct1);

    printf("-- Test block 1: Sequential 1-16\n");
    print_block("Input", block1);
    print_block("Forward DCT", dct1);
    print_block("Inverse DCT (roundtrip)", idct1);

    // Compute max roundtrip error
    int max_err1 = 0;
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++) {
            int err = abs(idct1[i][j] - block1[i][j]);
            if (err > max_err1) max_err1 = err;
        }
    printf("  -- Max roundtrip error: %d\n\n", max_err1);

    // Test block 2: Typical residual with negative values
    int block2[4][4] = {
        {  3, -1,  0,  2},
        { -2,  4, -3,  1},
        {  0,  1, -1,  0},
        {  1, -2,  3, -4}
    };

    int dct2[4][4], idct2[4][4];
    forward_dct_4x4(block2, dct2);
    inverse_dct_4x4(dct2, idct2);

    printf("-- Test block 2: Mixed positive/negative residuals\n");
    print_block("Input", block2);
    print_block("Forward DCT", dct2);
    print_block("Inverse DCT (roundtrip)", idct2);

    int max_err2 = 0;
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++) {
            int err = abs(idct2[i][j] - block2[i][j]);
            if (err > max_err2) max_err2 = err;
        }
    printf("  -- Max roundtrip error: %d\n\n", max_err2);

    // Test block 3: All zeros
    int block3[4][4] = {{0}};
    int dct3[4][4], idct3[4][4];
    forward_dct_4x4(block3, dct3);
    inverse_dct_4x4(dct3, idct3);

    printf("-- Test block 3: All zeros\n");
    print_block("Input", block3);
    print_block("Forward DCT", dct3);
    print_block("Inverse DCT (roundtrip)", idct3);

    return 0;
}
