/*
 * H.264 Intra_4×4 Prediction — Golden Reference Generator
 *
 * All 9 prediction modes for Intra_4×4:
 *   0: Vertical, 1: Horizontal, 2: DC
 *   3: Diagonal Down-Left, 4: Diagonal Down-Right
 *   5: Vertical-Right, 6: Horizontal-Down
 *   7: Vertical-Left, 8: Horizontal-Up
 *
 * Neighbor layout:
 *   M A B C D E F G H   (A-D = above, E-H = above-right, M = above-left)
 *   I x x x x            (I-L = left)
 *   J x x x x
 *   K x x x x
 *   L x x x x
 */

#include <cstdio>
#include <cstdlib>
#include <cstring>

// Neighbor pixels for a 4×4 block
struct Neighbors {
    uint8_t above[8];      // A(0)-H(7)
    uint8_t left[4];       // I(0)-L(3)
    uint8_t aboveLeft;     // M
    bool hasAbove;
    bool hasLeft;
    bool hasAboveRight;
};

// Predicted 4×4 block
typedef uint8_t Block4x4[4][4];

void predict_intra4x4(int mode, const Neighbors& n, Block4x4 pred) {
    uint8_t A = n.above[0], B = n.above[1], C = n.above[2], D = n.above[3];
    uint8_t E = n.above[4], F = n.above[5], G = n.above[6], H = n.above[7];
    uint8_t I = n.left[0], J = n.left[1], K = n.left[2], L = n.left[3];
    uint8_t M = n.aboveLeft;

    switch (mode) {
    case 0: // Vertical
        for (int i = 0; i < 4; i++)
            for (int j = 0; j < 4; j++)
                pred[i][j] = n.above[j];
        break;
    case 1: // Horizontal
        for (int i = 0; i < 4; i++)
            for (int j = 0; j < 4; j++)
                pred[i][j] = n.left[i];
        break;
    case 2: { // DC
        int sum = 0, count = 0;
        if (n.hasAbove) { sum += A + B + C + D; count += 4; }
        if (n.hasLeft) { sum += I + J + K + L; count += 4; }
        uint8_t dc = (count > 0) ? (sum + count/2) / count : 128;
        for (int i = 0; i < 4; i++)
            for (int j = 0; j < 4; j++)
                pred[i][j] = dc;
        break;
    }
    case 3: // Diagonal Down-Left
        pred[0][0] = (A + 2*B + C + 2) >> 2;
        pred[0][1] = pred[1][0] = (B + 2*C + D + 2) >> 2;
        pred[0][2] = pred[1][1] = pred[2][0] = (C + 2*D + E + 2) >> 2;
        pred[0][3] = pred[1][2] = pred[2][1] = pred[3][0] = (D + 2*E + F + 2) >> 2;
        pred[1][3] = pred[2][2] = pred[3][1] = (E + 2*F + G + 2) >> 2;
        pred[2][3] = pred[3][2] = (F + 2*G + H + 2) >> 2;
        pred[3][3] = (G + 2*H + H + 2) >> 2;  // H.264 spec uses H for out-of-range
        break;
    default:
        memset(pred, 128, sizeof(Block4x4));
        break;
    }
}

void print_block(const char* name, Block4x4 block) {
    printf("  -- %s\n  #[", name);
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++) {
            if (i > 0 || j > 0) printf(", ");
            printf("%d", block[i][j]);
        }
    printf("]\n");
}

int main() {
    printf("-- H.264 Intra 4×4 Prediction Golden Values\n");
    printf("-- Generated by generate_intrapred_golden.cpp\n\n");

    Neighbors n;
    n.above[0] = 10; n.above[1] = 20; n.above[2] = 30; n.above[3] = 40;
    n.above[4] = 50; n.above[5] = 60; n.above[6] = 70; n.above[7] = 80;
    n.left[0] = 15; n.left[1] = 25; n.left[2] = 35; n.left[3] = 45;
    n.aboveLeft = 5;
    n.hasAbove = true; n.hasLeft = true; n.hasAboveRight = true;

    printf("-- Neighbors: above=[10,20,30,40,50,60,70,80], left=[15,25,35,45], M=5\n\n");

    const char* modeNames[] = {
        "Vertical", "Horizontal", "DC", "Diagonal Down-Left"
    };

    for (int mode = 0; mode < 4; mode++) {
        Block4x4 pred;
        predict_intra4x4(mode, n, pred);
        printf("-- Mode %d: %s\n", mode, modeNames[mode]);
        print_block("Predicted", pred);
        printf("\n");
    }

    return 0;
}
