/*
 * H.264 NAL Unit Packing/Parsing — Golden Reference Generator
 *
 * NAL header: forbidden_zero_bit(1) | nal_ref_idc(2) | nal_unit_type(5)
 * Start code prefix: 0x000001
 * Emulation prevention: insert 0x03 after 0x0000 in payload
 */

#include <cstdio>
#include <cstdlib>
#include <vector>

using namespace std;

// NAL unit types (H.264 Table 7-1)
enum NalUnitType {
    NAL_SLICE_IDR = 5,
    NAL_SPS = 7,
    NAL_PPS = 8,
};

// Pack payload into NAL unit with start code and emulation prevention
vector<uint8_t> nal_pack(const vector<uint8_t>& payload, uint8_t nal_type, uint8_t nal_ref_idc) {
    vector<uint8_t> result;

    // Start code prefix
    result.push_back(0x00);
    result.push_back(0x00);
    result.push_back(0x01);

    // NAL header
    uint8_t header = (nal_ref_idc << 5) | nal_type;
    result.push_back(header);

    // Payload with emulation prevention
    int zeros = 0;
    for (uint8_t byte : payload) {
        if (zeros >= 2 && byte <= 0x03) {
            result.push_back(0x03);  // emulation prevention byte
            zeros = 0;
        }
        result.push_back(byte);
        if (byte == 0x00) zeros++;
        else zeros = 0;
    }

    return result;
}

// Parse NAL unit: remove start code and emulation prevention bytes
vector<uint8_t> nal_parse(const vector<uint8_t>& nal_unit) {
    vector<uint8_t> payload;

    // Skip start code (0x000001) and NAL header (1 byte)
    size_t start = 4;
    if (nal_unit.size() < 4) return payload;

    // Remove emulation prevention bytes (0x03 after 0x0000)
    int zeros = 0;
    for (size_t i = start; i < nal_unit.size(); i++) {
        if (zeros >= 2 && nal_unit[i] == 0x03) {
            zeros = 0;
            continue;  // skip emulation prevention byte
        }
        payload.push_back(nal_unit[i]);
        if (nal_unit[i] == 0x00) zeros++;
        else zeros = 0;
    }

    return payload;
}

void print_bytes(const char* name, const vector<uint8_t>& data) {
    printf("  -- %s (%zu bytes): [", name, data.size());
    for (size_t i = 0; i < data.size(); i++) {
        if (i > 0) printf(", ");
        printf("0x%02x", data[i]);
    }
    printf("]\n");
}

int main() {
    printf("-- H.264 NAL Unit Golden Values\n");
    printf("-- Generated by generate_nal_golden.cpp\n\n");

    // Test 1: Simple payload (no emulation prevention needed)
    vector<uint8_t> payload1 = {0x01, 0x02, 0x03, 0x04};
    auto nal1 = nal_pack(payload1, NAL_SLICE_IDR, 3);
    auto parsed1 = nal_parse(nal1);

    printf("-- Test 1: Simple payload\n");
    print_bytes("Payload", payload1);
    print_bytes("NAL unit", nal1);
    print_bytes("Parsed", parsed1);
    printf("  -- Roundtrip: %s\n\n", (payload1 == parsed1) ? "true" : "false");

    // Test 2: Payload with 0x0000 sequence (needs emulation prevention)
    vector<uint8_t> payload2 = {0x00, 0x00, 0x01, 0xFF};
    auto nal2 = nal_pack(payload2, NAL_SLICE_IDR, 3);
    auto parsed2 = nal_parse(nal2);

    printf("-- Test 2: Payload with 0x000001 (needs emulation prevention)\n");
    print_bytes("Payload", payload2);
    print_bytes("NAL unit", nal2);
    print_bytes("Parsed", parsed2);
    printf("  -- Roundtrip: %s\n\n", (payload2 == parsed2) ? "true" : "false");

    // Test 3: Payload with 0x000000 sequence
    vector<uint8_t> payload3 = {0x00, 0x00, 0x00, 0xAA};
    auto nal3 = nal_pack(payload3, NAL_SLICE_IDR, 3);
    auto parsed3 = nal_parse(nal3);

    printf("-- Test 3: Payload with 0x000000 (needs emulation prevention)\n");
    print_bytes("Payload", payload3);
    print_bytes("NAL unit", nal3);
    print_bytes("Parsed", parsed3);
    printf("  -- Roundtrip: %s\n\n", (payload3 == parsed3) ? "true" : "false");

    // Test 4: Empty payload
    vector<uint8_t> payload4 = {};
    auto nal4 = nal_pack(payload4, NAL_SPS, 3);
    auto parsed4 = nal_parse(nal4);

    printf("-- Test 4: Empty payload\n");
    print_bytes("Payload", payload4);
    print_bytes("NAL unit", nal4);
    print_bytes("Parsed", parsed4);
    printf("  -- Roundtrip: %s\n", (payload4 == parsed4) ? "true" : "false");

    return 0;
}
