/-
  C Simulation Backend Tests

  Tests that the CSim backend generates correct C code from IR modules.
  (Kept under the legacy filename to minimise churn for `Tests.AllTests`;
  the namespace is renamed to `Sparkle.Test.CSim` so post-rename
  consistency is preserved.)
-/

import Sparkle.Backend.CSim
import Sparkle.Compiler.Elab
import Sparkle.IR.AST
import Sparkle.IR.Type
import Sparkle.IR.Builder
import Sparkle.IR.Specialize
import Tests.SymbolicParameterCircuits
import LSpec

namespace Sparkle.Test.CppSim

open Sparkle.Backend.CSim
open Sparkle.IR.AST
open Sparkle.IR.Type
open Sparkle.IR.Builder
open Sparkle.IR.Specialize
open CircuitM
open LSpec

/-- Check if a string contains a substring -/
private def hasSubstr (s : String) (sub : String) : Bool :=
  decide ((s.splitOn sub).length > 1)

/-- Check that a failed specialization reports every stable diagnostic token. -/
private def errorContainsAll {α : Type} (result : Except String α)
    (needles : List String) : Bool :=
  match result with
  | .ok _ => false
  | .error message => needles.all (hasSubstr message)

/-- A retained-width XOR fixture.  Concrete C models must be generated by
    specializing this module first; sending it directly to CSim remains an
    error. -/
def symbolicXorModule : Module := {
  name := "SymbolicXor"
  parameters := [{ name := "W", defaultValue := 8 }]
  inputs := [
    ⟨"lhs", .bitVectorDim (.parameter "W")⟩,
    ⟨"rhs", .bitVectorDim (.parameter "W")⟩
  ]
  outputs := [⟨"out", .bitVectorDim (.parameter "W")⟩]
  wires := []
  body := [.assign "out" (.op .xor [.ref "lhs", .ref "rhs"])]
}

def symbolicXorDesign : Design :=
  { topModule := symbolicXorModule.name, modules := [symbolicXorModule] }

/-- Exercises both a derived port width (`W + 1`) and a symbolic slice bound
    (`W - 1`).  A port-only substitution would pass the XOR fixture but fail
    this one. -/
def symbolicSliceModule : Module := {
  name := "SymbolicSlice"
  parameters := [{ name := "W", defaultValue := 8 }]
  inputs := [
    ⟨"x", .bitVectorDim (.add (.parameter "W") (.literal 1))⟩
  ]
  outputs := [⟨"out", .bitVectorDim (.parameter "W")⟩]
  wires := []
  body := [
    .assign "out"
      (.sliceDim (.ref "x")
        (.sub (.parameter "W") (.literal 1)) (.literal 0))
  ]
}

/-- Concrete zero-bit wires are bookkeeping for Unit/HList synthesis and must
    survive specialization until the normal optimizer removes them. -/
def zeroWidthBookkeepingModule : Module := {
  name := "ZeroWidthBookkeeping"
  parameters := [{ name := "W", defaultValue := 8 }]
  inputs := [⟨"x", .bitVectorDim (.parameter "W")⟩]
  outputs := [⟨"out", .bitVectorDim (.parameter "W")⟩]
  wires := [⟨"_unit_bookkeeping", .bitVector 0⟩]
  body := [.assign "out" (.ref "x")]
}

/-- A declared parameter need not appear in a width expression.  Its explicit
    binding still obeys the positive-width contract. -/
def unusedRetainedParameterModule : Module := {
  name := "UnusedRetainedParameter"
  parameters := [{ name := "W", defaultValue := 8 }]
  inputs := [⟨"x", .bitVector 8⟩]
  outputs := [⟨"out", .bitVector 8⟩]
  wires := []
  body := [.assign "out" (.ref "x")]
}

private def portHasType (ports : List Port) (name : String) (ty : HWType) : Bool :=
  ports.any fun port => port.name == name && port.ty == ty

private def hasConcreteSlice (module : Module) (hi lo : Nat) : Bool :=
  module.body.any fun statement => match statement with
    | .assign "out" (.slice (.ref "x") actualHi actualLo) =>
        actualHi == hi && actualLo == lo
    | _ => false

private def dimensionEvaluatesTo (dimension : DimExpr)
    (bindings : Bindings) (expected : Nat) : Bool :=
  match dimension.evaluate bindings with
  | .ok actual => actual == expected
  | .error _ => false

private def specializedXor (width : Nat) : Except String Module :=
  specializeModule symbolicXorModule [("W", width)]

private def specializedXorC (width : Nat) : String :=
  match toCWithParameters symbolicXorModule [("W", width)] with
  | .ok cSource => cSource
  | .error _ => ""


private def concreteXorHasWidth (width : Nat) : Bool :=
  match specializedXor width with
  | .error _ => false
  | .ok module =>
      module.parameters.isEmpty &&
      portHasType module.inputs "lhs" (.bitVector width) &&
      portHasType module.inputs "rhs" (.bitVector width) &&
      portHasType module.outputs "out" (.bitVector width) &&
      !moduleHasSymbolicWidth module

private def specializedXorDesignC (width : Nat) : String :=
  match toCDesignWithParameters symbolicXorDesign [("W", width)] with
  | .ok cSource => cSource
  | .error _ => ""

/-- Result of the end-to-end compiler regression: the Lean compiler must first
    retain W symbolically (with an unrelated Verilog default of 8), then CSim
    must explicitly specialize that same IR to W=17. -/
structure LeanParameterizedCSimOutput where
  retainedSymbolicWidth : Bool
  c17 : String

def synthesizeLeanParameterizedXorCSim : Lean.MetaM LeanParameterizedCSimOutput := do
  let (hardwareModule, partialDesign) ←
    Sparkle.Compiler.Elab.synthesizeCombinationalWithParameters
      `symbolicXor [("W", 8)]
  let retainedSymbolicWidth :=
    hardwareModule.parameters.any fun parameter =>
      parameter.name == "W" && parameter.defaultValue == 8
    && moduleHasSymbolicWidth hardwareModule
  let completeDesign :=
    if partialDesign.modules.any (·.name == hardwareModule.name) then
      { partialDesign with topModule := hardwareModule.name }
    else
      { (partialDesign.addModule hardwareModule) with
        topModule := hardwareModule.name }
  let c17 ← match toCDesignWithParameters completeDesign [("W", 17)] with
    | .ok cSource => pure cSource
    | .error message => throwError message
  return { retainedSymbolicWidth, c17 }

/-- Build a counter module: clk, rst, en → 8-bit count_out -/
def counterModule : Module :=
  runModule "Counter8" do
    addInput "clk" .bit
    addInput "rst" .bit
    addInput "en" (.bitVector 8)
    addOutput "count_out" (.bitVector 8)
    let inc ← makeWire "inc" (.bitVector 8)
    let count ← emitRegister "count" "clk" "rst" (.ref inc) 0 (.bitVector 8)
    emitAssign inc (.op .add [.ref count, .const 1 8])
    let next ← makeWire "next" (.bitVector 8)
    emitAssign next (.op .mux [.ref "en", .ref inc, .ref count])
    emitAssign "count_out" (.ref count)

/-- Build a memory module: write addr/data/en, read addr → read data -/
def memoryModule : Module :=
  runModule "MemTest" do
    addInput "clk" .bit
    addInput "rst" .bit
    addInput "wr_addr" (.bitVector 4)
    addInput "wr_data" (.bitVector 8)
    addInput "wr_en" .bit
    addInput "rd_addr" (.bitVector 4)
    addOutput "rd_data" (.bitVector 8)
    let rdWire ← emitMemoryComboRead "mem" 4 8 "clk"
      (.ref "wr_addr") (.ref "wr_data") (.ref "wr_en") (.ref "rd_addr")
    emitAssign "rd_data" (.ref rdWire)

/-- Build a combinational module: a, b → add_out, and_out, mux_out -/
def combModule : Module :=
  runModule "CombOps" do
    addInput "a" (.bitVector 8)
    addInput "b" (.bitVector 8)
    addInput "sel" .bit
    addOutput "add_out" (.bitVector 8)
    addOutput "and_out" (.bitVector 8)
    addOutput "mux_out" (.bitVector 8)
    emitAssign "add_out" (.op .add [.ref "a", .ref "b"])
    emitAssign "and_out" (.op .and [.ref "a", .ref "b"])
    emitAssign "mux_out" (.op .mux [.ref "sel", .ref "a", .ref "b"])

/-- Build a module with registered (non-combo) memory read -/
def registeredMemModule : Module :=
  runModule "RegMemTest" do
    addInput "clk" .bit
    addInput "rst" .bit
    addInput "wr_addr" (.bitVector 4)
    addInput "wr_data" (.bitVector 8)
    addInput "wr_en" .bit
    addInput "rd_addr" (.bitVector 4)
    addOutput "rd_data" (.bitVector 8)
    let rdWire ← emitMemory "rmem" 4 8 "clk"
      (.ref "wr_addr") (.ref "wr_data") (.ref "wr_en") (.ref "rd_addr")
    emitAssign "rd_data" (.ref rdWire)

def cppSimTests (leanOutput : LeanParameterizedCSimOutput) : IO TestSeq := do
  let counterC := toC counterModule
  let memoryC := toC memoryModule
  let combC := toC combModule
  let regMemC := toC registeredMemModule
  let xor3C := specializedXorC 3
  let xor17C := specializedXorC 17
  let xor65C := specializedXorC 65
  let xor17DesignC := specializedXorDesignC 17
  let xor17JITC := match toCJITWithParameters symbolicXorDesign [("W", 17)] with
    | .ok cSource => cSource
    | .error _ => ""
  let slice17 := specializeModule symbolicSliceModule [("W", 17)]
  let slice17C := match toCWithParameters symbolicSliceModule [("W", 17)] with
    | .ok cSource => cSource
    | .error _ => ""
  let slice17IsConcrete : Bool := match slice17 with
    | .error _ => false
    | .ok hardwareModule =>
        hardwareModule.parameters.isEmpty &&
        portHasType hardwareModule.inputs "x" (.bitVector 18) &&
        portHasType hardwareModule.outputs "out" (.bitVector 17) &&
        hasConcreteSlice hardwareModule 16 0 &&
        !moduleHasSymbolicWidth hardwareModule
  let zeroWidthBookkeepingPreserved : Bool :=
    match specializeModule zeroWidthBookkeepingModule [("W", 3)] with
    | .error _ => false
    | .ok hardwareModule =>
        hardwareModule.parameters.isEmpty &&
        portHasType hardwareModule.wires "_unit_bookkeeping" (.bitVector 0) &&
        !moduleHasSymbolicWidth hardwareModule

  return group "C Simulation Backend Tests" (
    group "Parameterized width specialization" (
      group "Lean compiler integration" (
        test "compiler retains W instead of freezing its default"
          leanOutput.retainedSymbolicWidth $
        test "retained W can be explicitly specialized to 17 for CSim"
          (hasSubstr leanOutput.c17 "struct symbolicXor" &&
           hasSubstr leanOutput.c17 "uint32_t _gen_lhs;" &&
           hasSubstr leanOutput.c17 "uint32_t _gen_rhs;" &&
           !hasSubstr leanOutput.c17 "uint8_t _gen_lhs;" &&
           !hasSubstr leanOutput.c17 "#error")
      ) ++
      group "explicit W sweep" (
        test "W=3 emits a concrete uint8_t model"
          (concreteXorHasWidth 3 &&
           hasSubstr xor3C "uint8_t lhs;" &&
           hasSubstr xor3C "uint8_t rhs;" &&
           hasSubstr xor3C "uint8_t out;" &&
           hasSubstr xor3C "self->lhs &= 0x7ULL;" &&
           hasSubstr xor3C "self->rhs &= 0x7ULL;" &&
           !hasSubstr xor3C "SPARKLE_UNSUPPORTED_SYMBOLIC_WIDTH") $
        test "W=17 emits a concrete uint32_t model"
          (concreteXorHasWidth 17 &&
           hasSubstr xor17C "uint32_t lhs;" &&
           hasSubstr xor17C "uint32_t rhs;" &&
           hasSubstr xor17C "uint32_t out;" &&
           hasSubstr xor17C "self->lhs &= 0x1ffffULL;" &&
           hasSubstr xor17C "self->rhs &= 0x1ffffULL;" &&
           !hasSubstr xor17C "SPARKLE_UNSUPPORTED_SYMBOLIC_WIDTH") $
        test "W=65 emits three-word packed ports"
          (concreteXorHasWidth 65 &&
           hasSubstr xor65C "uint32_t lhs[3];" &&
           hasSubstr xor65C "uint32_t rhs[3];" &&
           hasSubstr xor65C "uint32_t out[3];" &&
           !hasSubstr xor65C "SPARKLE_UNSUPPORTED_SYMBOLIC_WIDTH") $
        test "design API feeds a concrete module to CSim"
          (hasSubstr xor17DesignC "struct SymbolicXor" &&
           hasSubstr xor17DesignC "uint32_t lhs;" &&
           !hasSubstr xor17DesignC "#error") $
        test "parameterized JIT API emits its concrete vtable"
          (hasSubstr xor17JITC "const JitVTable* jit_vtable" &&
           hasSubstr xor17JITC "struct SymbolicXor" &&
           !hasSubstr xor17JITC "#error")
      ) ++
      group "derived dimensions" (
        test "W+1 ports and W-1 slice bounds become concrete"
          slice17IsConcrete $
        test "derived-width module reaches CSim without symbolic markers"
          (hasSubstr slice17C "struct SymbolicSlice" &&
           !hasSubstr slice17C "SPARKLE_UNSUPPORTED_SYMBOLIC")
      ) ++
      group "specialization invariants" (
        test "preserves concrete zero-bit bookkeeping until optimization"
          zeroWidthBookkeepingPreserved $
        test "rejects zero for an unused retained parameter"
          (errorContainsAll
            (specializeModule unusedRetainedParameterModule [("W", 0)])
            ["W", "zero", "positive"])
      ) ++
      group "dimension expression evaluation" (
        test "evaluates derived arithmetic through clog2"
          (dimensionEvaluatesTo
            (.clog2 (.add (.mul (.parameter "W") (.literal 2)) (.literal 1)))
            [("W", 8)] 5) $
        test "rejects subtraction underflow"
          (errorContainsAll
            ((.sub (.literal 3) (.parameter "W") : DimExpr).evaluate [("W", 4)])
            ["subtraction", "underflow"]) $
        test "rejects division by zero"
          (errorContainsAll
            ((.div (.parameter "W") (.literal 0) : DimExpr).evaluate [("W", 8)])
            ["division", "zero"]) $
        test "rejects modulo by zero"
          (errorContainsAll
            ((.mod (.parameter "W") (.literal 0) : DimExpr).evaluate [("W", 8)])
            ["modulo", "zero"])
      ) ++
      group "fail-closed diagnostics" (
        test "direct symbolic CSim emission remains rejected"
          (hasSubstr (toC symbolicXorModule)
            "Sparkle CSim requires concrete widths") $
        test "rejects a missing explicit binding"
          (errorContainsAll (toCWithParameters symbolicXorModule []) ["missing", "W"]) $
        test "rejects an unknown binding"
          (errorContainsAll
            (toCWithParameters symbolicXorModule [("W", 3), ("UNKNOWN", 9)])
            ["unknown", "UNKNOWN"]) $
        test "rejects duplicate bindings"
          (errorContainsAll
            (toCWithParameters symbolicXorModule [("W", 3), ("W", 17)])
            ["duplicate", "W"]) $
        test "rejects a zero hardware width"
          (errorContainsAll
            (toCWithParameters symbolicXorModule [("W", 0)])
            ["zero", "width"])
      )
    ) ++
    group "Counter Module" (
      test "has struct declaration" (hasSubstr counterC "struct Counter8") $
      test "has eval helper" (hasSubstr counterC "sparkle_Counter8_eval") $
      test "has tick helper" (hasSubstr counterC "sparkle_Counter8_tick") $
      test "has reset helper" (hasSubstr counterC "sparkle_Counter8_reset") $
      test "has uint8_t port type" (hasSubstr counterC "uint8_t") $
      test "normalizes one-bit C ABI inputs before evaluation"
        (hasSubstr counterC "self->clk &= 1u;" &&
         hasSubstr counterC "self->rst &= 1u;") $
      test "has _next suffix for register" (hasSubstr counterC "_next") $
      test "has addition operator" (hasSubstr counterC " + ") $
      test "has ternary for mux" (hasSubstr counterC " ? ") $
      test "has stdint header" (hasSubstr counterC "#include <stdint.h>")
    ) ++
    group "Memory Module" (
      test "has struct declaration" (hasSubstr memoryC "struct MemTest") $
      test "has plain C array for memory" (hasSubstr memoryC "[16]") $
      test "has memset in reset" (hasSubstr memoryC "memset(") $
      test "has eval helper" (hasSubstr memoryC "sparkle_MemTest_eval") $
      test "has tick helper" (hasSubstr memoryC "sparkle_MemTest_tick")
    ) ++
    group "Combinational Module" (
      test "has struct declaration" (hasSubstr combC "struct CombOps") $
      test "has addition" (hasSubstr combC " + ") $
      test "has bitwise AND" (hasSubstr combC " & ") $
      test "has ternary for mux" (hasSubstr combC " ? ") $
      test "has uint8_t types" (hasSubstr combC "uint8_t")
    ) ++
    group "Registered Memory Module" (
      test "has struct declaration" (hasSubstr regMemC "struct RegMemTest") $
      test "has plain C array" (hasSubstr regMemC "[16]") $
      test "has read addr latch" (hasSubstr regMemC "_raddr")
    )
  )

end Sparkle.Test.CppSim
