/-
  Sim test for IP.TLS.X509.parseCertificate against three
  real-world certs generated by OpenSSL 3.6.2 (one per
  TLS 1.3 sig algorithm: Ed25519, ECDSA-P256, RSA-2048).

  The DER blobs live as binary files alongside this source
  (`ed25519-cert.der`, `p256-cert.der`, `rsa-cert.der`) and
  are read at test time.
-/

import IP.TLS.X509

open Sparkle.IP.TLS.X509

namespace Sparkle.Tests.IP.TLS.X509ParserTest

/-- Read a `.der` file (relative to this test source's
    directory) as `Array UInt8`. -/
private def readDer (relPath : String) : IO (Array UInt8) := do
  let path : System.FilePath :=
    System.FilePath.mk ("Tests/IP/TLS/" ++ relPath)
  let bytes ← IO.FS.readBinFile path
  -- ByteArray → Array UInt8.
  let mut out : Array UInt8 := Array.replicate bytes.size 0
  for i in [:bytes.size] do
    out := out.set! i bytes[i]!
  return out

def main : IO Unit := do
  IO.println "=== X.509 DER parser sim ==="

  let mut ok := true

  -- ────────────────────────────────────────────────
  IO.println "\n1. Ed25519 cert:"
  let ed25519Bytes ← readDer "ed25519-cert.der"
  IO.println s!"  cert size = {ed25519Bytes.size} bytes"
  match parseCertificate ed25519Bytes with
  | none =>
    IO.println "  ✗ parse failed"; ok := false
  | some cert =>
    IO.println s!"  version       = {cert.version}"
    IO.println s!"  serialNumber  = {cert.serialNumber}"
    IO.println s!"  notBefore     = {cert.validity.notBefore}"
    IO.println s!"  notAfter      = {cert.validity.notAfter}"
    IO.println s!"  pubkey algo   = {repr cert.spki.algorithm}"
    IO.println s!"  rawKey size   = {cert.spki.rawKey.size}"
    IO.println s!"  tbsBegin..End = {cert.tbsBegin}..{cert.tbsEnd}"
    IO.println s!"  sig bytes     = {cert.signature.size}"
    if cert.version = 2 ∧
       cert.spki.algorithm == PublicKeyAlg.ed25519 ∧
       cert.spki.rawKey.size = 32 then
      IO.println "  ✓ ed25519 cert parsed correctly"
    else
      IO.println "  ✗ unexpected fields"; ok := false

  -- ────────────────────────────────────────────────
  IO.println "\n2. ECDSA-P256 cert:"
  let p256Bytes ← readDer "p256-cert.der"
  IO.println s!"  cert size = {p256Bytes.size} bytes"
  match parseCertificate p256Bytes with
  | none =>
    IO.println "  ✗ parse failed"; ok := false
  | some cert =>
    IO.println s!"  version       = {cert.version}"
    IO.println s!"  pubkey algo   = {repr cert.spki.algorithm}"
    IO.println s!"  rawKey size   = {cert.spki.rawKey.size} (expect 65)"
    IO.println s!"  raw[0]        = 0x{cert.spki.rawKey[0]!.toNat |> Nat.toDigits 16 |> String.ofList}"
    if cert.version = 2 ∧
       cert.spki.algorithm == PublicKeyAlg.ecdsaP256 ∧
       cert.spki.rawKey.size = 65 ∧
       cert.spki.rawKey[0]! = 0x04 then
      IO.println "  ✓ p256 cert parsed correctly"
    else
      IO.println "  ✗ unexpected fields"; ok := false

  -- ────────────────────────────────────────────────
  IO.println "\n3. RSA-2048 cert:"
  let rsaBytes ← readDer "rsa-cert.der"
  IO.println s!"  cert size = {rsaBytes.size} bytes"
  match parseCertificate rsaBytes with
  | none =>
    IO.println "  ✗ parse failed"; ok := false
  | some cert =>
    IO.println s!"  version       = {cert.version}"
    IO.println s!"  pubkey algo   = {repr cert.spki.algorithm}"
    IO.println s!"  rawKey size   = {cert.spki.rawKey.size} (DER-encoded RSAPublicKey)"
    if cert.version = 2 ∧
       cert.spki.algorithm == PublicKeyAlg.rsa ∧
       cert.spki.rawKey.size > 200 then
      IO.println "  ✓ rsa cert parsed correctly"
    else
      IO.println "  ✗ unexpected fields"; ok := false

  if ok then
    IO.println "\nALL PASS"
  else
    IO.println "\nFAIL"
    IO.Process.exit 1

end Sparkle.Tests.IP.TLS.X509ParserTest
