// Generated by Sparkle HDL
// Module: blinkyTop

module blinkyTop (
    input logic _gen_en,
    input logic clk,
    input logic rst,
    output logic [24:0] out
);

    logic [24:0] _tmp_a_1;
    logic [24:0] _gen_inc;
    logic [24:0] _tmp_reg_input_5;
    logic [24:0] _tmp_a_6;
    logic [24:0] _gen_out;


    assign _tmp_a_1 = _tmp_a_6;

    assign _gen_inc = (_tmp_a_1 + 25'd1);

    assign _tmp_reg_input_5 = (_gen_en ? _gen_inc : _tmp_a_1);

    always_ff @(posedge clk) begin
        if (rst)
            _tmp_a_6 <= 25'd0;
        else
            _tmp_a_6 <= _tmp_reg_input_5;
    end

    assign _gen_out = _tmp_a_6;

    assign out = _gen_out;

endmodule
