import Sparkle
import Sparkle.Core.CircuitMonad
import Sparkle.Core.CircuitDo
import IP.Net.CRC32
import IP.Net.UART
import Tools.DeepElab

/-!
  `#verify_elab_deep` on REAL shipping IP — not demo circuits.

  Each success here is an instance of the general Signal↔IR theorem
  (`Cdo.elab_general`) on a production circuit: the cycle-by-cycle
  Signal semantics of the shipped DSL definition equals the proven
  IR evaluator on its compiled next-state/output cones.

  Current real-IP coverage:
  * `crc32Engine` — CRC-32 byte engine (IP/Net): xor/shr/and/sub/
    concat/mux over 32 bits, a private two-level helper chain
    (`crc32StepSig` → 8 × `crc32BitSig`) unfolded via the collected-
    helper mechanism, plus a private `abbrev poly : BitVec 32`
    constant (closed BitVec constants ride along with the helpers).
  * `uartTxHW` — UART transmitter (IP/Net): 4 registers (10/4/16-bit
    plus a Bool `busy`), 3 inputs (one Bool), a struct output `TxOut`
    with two Bool ports, literal-width `++` ascriptions.  The first
    circuit with a register index ≥ 3 — the case that forced the
    Signal-side bridge onto literal-width readers (`{f}_deep_rd{i}`)
    instead of `Cdo.stateAt`'s `Γr.get i`-typed values.

  Known boundaries (each is a worklist item, not a silent skip):
  * non-Signal value parameters (`biquad`'s `lim`, `mulQSig`'s
    `w f`) go through a specialized wrapper def, as for synthesis
    (demos `accK15` / `accN200` in DeepElabReifyDemo);
  * arithmetic size: `closedLoopCircuit` (PID + plant, 32/64-bit
    fixed-point multiplies, nested; 3 registers once RegDedup merges
    the two-pass copies) times out in the definition phase (`isDefEq`
    on the multiply cones) before the bridge runs — the nesting itself
    is covered by the `DeepElabReifyDemo` nested demos.
-/

namespace Sparkle.Tests.DeepElabRealIP

open Sparkle.IP.Net.CRC32 Sparkle.IP.Net.UART

#verify_elab_deep crc32Engine
#verify_elab_deep uartTxHW

/-- The theorems above are build-time facts; the exe is a formality
    so `lake build` has an anchor. -/
def main : IO Unit := do
  IO.println "deep-elab real-IP: crc32Engine, uartTxHW PROVEN (build-time)"


-- deep-bridge replay pins: the general-theorem route's per-instance
-- chain (seed bound → register phase → cycle trace → Signal ≡ runModule),
-- generated by #verify_elab_deep and audited against sorryAx
#check @crc32Engine_deep_seed_bounded
#check @crc32Engine_deep_regstep
#check @crc32Engine_deep_state_trace
#check @crc32Engine_deep_signal_fold
#check @crc32Engine_deep_signal_run

-- uart: the capstone per struct port, the shared register chain, and
-- the literal-width readers the Signal-side bridge is stated over
#check @uartTxHW_txLine_deep_trace
#check @uartTxHW_txReady_deep_trace
#check @uartTxHW_txLine_deep_rd3_succ
#check @uartTxHW_deep_seed_bounded
#check @uartTxHW_deep_regstep
#check @uartTxHW_deep_state_trace
#check @uartTxHW_txLine_deep_signal_run
#check @uartTxHW_txReady_deep_signal_run

end Sparkle.Tests.DeepElabRealIP
