/-
  SimVerilator — Verilator backend for the unified `Sim` typeclass.

  Verilator's native build model is `verilator --cc <design.sv> -o
  obj_dir/V<top>` followed by hand-written C++.  To plug into the
  same `Sim` interface as the JIT backend we wrap that pipeline so
  the resulting shared library exports the **same C ABI** the JIT
  uses: one symbol, `jit_vtable()`, returning the table of
  `create / eval_tick / set_input / get_output / reset / destroy / …`
  (the entries with no Verilator counterpart — named wires, memories,
  register access, snapshots — are inert).  Because the ABI matches, the
  existing `Sparkle.Core.JIT.JITHandle` opaque + FFI works
  unchanged — we just hand it a Verilator-backed `.so` instead of a
  CppSim-backed one.

  Build pipeline (offline, kicked off lazily by `load`):

  1.  `IO.FS.writeFile <svPath> <verilog>` — written by the user
      *before* calling `load`, e.g. via
      `Sparkle.Backend.Verilog.writeVerilogFile`.
  2.  `verilator --cc --build --top-module <top> -CFLAGS '-O2 -fPIC'
       --Mdir <objDir>/<top> <svPath> <tbCpp>`
      where `tbCpp` is the small wrapper this module emits.  This stops
      at static libraries (`libV<top>.a`, `libverilated.a`).
  3.  `c++ -shared -o V<top>.so --whole-archive libV<top>.a
       --no-whole-archive libverilated.a` — the shared object.
  4.  `JIT.load <so>` — the same dlopen path the CppSim backend uses.

  Outputs are sampled the way the JIT samples them: `read` after `step`
  returns the values the design showed BEFORE that clock edge, so a test
  sees every signal in the same cycle on both backends.

  The user-visible interface is one function:

      Verilator.of svPath topModule inputs outputs : IO Simulator

  plus the `Sim` instance.  We reuse the JIT FFI for the runtime
  calls so there is no second set of `extern "C"` bindings to
  maintain.
-/
import Sparkle.Core.JIT
import Sparkle.Core.Sim

namespace Sparkle.Core.Sim.Verilator

open Sparkle.Core.JIT

/-- One input port: name (matches the `.sv` port) and bit-width.
    The width drives the C++ type chosen for the `jit_set_input`
    switch case (`uint8_t`, `uint16_t`, `uint32_t`, or `uint64_t`). -/
structure PortSpec where
  name  : String
  width : Nat
  deriving Repr, Inhabited

/-- Verilator simulator state.  Just a `JITHandle` because the
    Verilator-backed `.so` exposes the JIT C ABI. -/
structure Simulator where
  handle : JITHandle

/-- Pick the smallest unsigned C type that holds `width` bits. -/
private def cTypeFor (width : Nat) : String :=
  if width ≤ 8 then "uint8_t"
  else if width ≤ 16 then "uint16_t"
  else if width ≤ 32 then "uint32_t"
  else "uint64_t"

/-- Emit the C++ testbench / FFI shim that wraps a Verilator
    `V<top>` model behind the JIT C ABI.  The resulting `.cpp`
    is compiled together with the Verilator-generated sources by
    `verilator --build`. -/
def emitTb (top : String) (inputs outputs : List PortSpec)
    (clock : String := "clk") (reset : Option (String × Bool) := some ("rst", true))
    (resetCycles : Nat := 1) : String :=
  let cls := s!"V{top}"
  -- `reset`: the reset port and whether it is active high.  A design
  -- written elsewhere may call it `aresetn` and want it low; a design
  -- without a reset port is created and left alone.
  let rstSet (active : Bool) : String := match reset with
    | some (r, activeHigh) => s!"m->{r} = {if active == activeHigh then 1 else 0}; "
    | none => ""
  let resetPulses := String.join <| (List.range (max resetCycles 1)).map fun _ =>
    s!"    m->{clock} = 1; m->eval();\n    m->{clock} = 0; m->eval();\n"
  -- Slot layout = the JIT C ABI's (`CSim.emitSetInputSwitch` /
  -- `emitGetOutputSwitch`): a port of up to 64 bits is one slot; a wider
  -- port is ⌈w/32⌉ consecutive 32-bit slots, low word first (Verilator
  -- stores it as an array of 32-bit words too).
  let slots (ports : List PortSpec) : List (String × Nat × Option Nat) :=
    ports.flatMap fun p =>
      if p.width ≤ 64 then [(p.name, p.width, none)]
      else (List.range ((p.width + 31) / 32)).map fun j => (p.name, p.width, some j)
  let inSlots := slots inputs
  let outSlots := slots outputs
  let setCases :=
    String.intercalate "\n" <|
      (List.range inSlots.length).zip inSlots |>.map fun (i, (name, width, word)) =>
        match word with
        | none => s!"        case {i}: m->{name} = ({cTypeFor width})val; break;"
        | some j => s!"        case {i}: m->{name}[{j}] = (uint32_t)val; break;"
  let snapLines :=
    String.intercalate "\n" <|
      (List.range outSlots.length).zip outSlots |>.map fun (i, (name, _, word)) =>
        match word with
        | none => s!"    c->out[{i}] = (uint64_t)c->m->{name};"
        | some j => s!"    c->out[{i}] = (uint64_t)c->m->{name}[{j}];"
  -- Stitch the wrapper.
  "// Auto-generated by Sparkle.Core.Sim.Verilator.\n" ++
  "// Exposes the JIT C ABI on top of a Verilator-built model.\n" ++
  "//\n" ++
  "// Output timing follows the JIT (CSim): `jit_get_output` returns the\n" ++
  "// outputs of the last EVALUATION — for `jit_eval_tick`, the values the\n" ++
  "// design shows in the cycle the inputs were applied, before the clock\n" ++
  "// edge.  Reading the model after the edge instead (as this wrapper once\n" ++
  "// did) is one cycle late for every registered output, and a ready/valid\n" ++
  "// handshake observed that way is the wrong one.\n" ++
  "#include \"" ++ cls ++ ".h\"\n" ++
  "#include <cstdint>\n\n" ++
  "struct SparkleVCtx { " ++ cls ++ "* m; uint64_t out[" ++ toString (max outSlots.length 1) ++ "]; };\n" ++
  "static void sparkle_snap(SparkleVCtx* c) {\n" ++
  "    (void)c;\n" ++ snapLines ++ "\n}\n\n" ++
  "extern \"C\" {\n\n" ++
  "void* jit_create() {\n" ++
  "    auto* c = new SparkleVCtx(); c->m = new " ++ cls ++ "(); auto* m = c->m;\n" ++
  "    m->" ++ clock ++ " = 0; " ++ rstSet false ++ "m->eval(); sparkle_snap(c);\n" ++
  "    return (void*)c;\n}\n" ++
  "void  jit_destroy(void* ctx) { auto* c = static_cast<SparkleVCtx*>(ctx); delete c->m; delete c; }\n\n" ++
  -- Reset: pulse rst high for one cycle, then low.  Matches the
  -- behaviour of the CppSim `reset()` member.
  "void  jit_reset(void* ctx) {\n" ++
  "    auto* c = static_cast<SparkleVCtx*>(ctx); auto* m = c->m;\n" ++
  "    " ++ rstSet true ++ "m->" ++ clock ++ " = 0; m->eval();\n" ++
  resetPulses ++
  "    " ++ rstSet false ++ "m->eval();\n" ++
  "    sparkle_snap(c);\n" ++
  "}\n\n" ++
  -- eval / tick / fused.
  "void jit_eval(void* ctx) {\n" ++
  "    auto* c = static_cast<SparkleVCtx*>(ctx); c->m->eval(); sparkle_snap(c);\n" ++
  "}\n" ++
  "void jit_tick(void* ctx) {\n" ++
  "    auto* m = static_cast<SparkleVCtx*>(ctx)->m;\n" ++
  "    m->" ++ clock ++ " = 1; m->eval();\n" ++
  "    m->" ++ clock ++ " = 0; m->eval();\n" ++
  "}\n\n" ++
  "void jit_eval_tick(void* ctx) {\n" ++
  "    auto* c = static_cast<SparkleVCtx*>(ctx); auto* m = c->m;\n" ++
  "    m->eval(); sparkle_snap(c);      // this cycle's outputs, inputs applied\n" ++
  "    m->" ++ clock ++ " = 1; m->eval();           // clock edge\n" ++
  "    m->" ++ clock ++ " = 0; m->eval();\n" ++
  "}\n\n" ++
  "void jit_set_input(void* ctx, uint32_t idx, uint64_t val) {\n" ++
  "    auto* m = static_cast<SparkleVCtx*>(ctx)->m;\n" ++
  "    switch (idx) {\n" ++
  setCases ++ "\n" ++
  "        default: break;\n    }\n}\n\n" ++
  "uint64_t jit_get_output(void* ctx, uint32_t idx) {\n" ++
  "    auto* c = static_cast<SparkleVCtx*>(ctx);\n" ++
  "    return idx < " ++ toString outSlots.length ++ "u ? c->out[idx] : 0;\n" ++
  "}\n\n" ++
  -- The loader resolves ONE symbol, `jit_vtable` (c_src/sparkle_jit.c);
  -- the table layout is CSim's `JitVTable`.  Wires, memories, registers
  -- and snapshots are not exposed by a Verilator model: those entries are
  -- inert.
  "typedef struct JitVTable {\n" ++
  "    void* (*create)(void);\n" ++
  "    void  (*destroy)(void* ctx);\n" ++
  "    void  (*reset)(void* ctx);\n" ++
  "    void  (*eval)(void* ctx);\n" ++
  "    void  (*tick)(void* ctx);\n" ++
  "    void  (*eval_tick)(void* ctx);\n" ++
  "    void  (*set_input)(void* ctx, uint32_t idx, uint64_t val);\n" ++
  "    uint64_t (*get_output)(void* ctx, uint32_t idx);\n" ++
  "    uint64_t (*get_wire)(void* ctx, uint32_t idx);\n" ++
  "    void  (*set_mem)(void* ctx, uint32_t mem_idx, uint32_t addr, uint32_t data);\n" ++
  "    uint32_t (*get_mem)(void* ctx, uint32_t mem_idx, uint32_t addr);\n" ++
  "    void  (*memset_word)(void* ctx, uint32_t mem_idx, uint32_t addr, uint32_t val, uint32_t count);\n" ++
  "    const char* (*wire_name)(uint32_t idx);\n" ++
  "    uint32_t (*num_wires)(void);\n" ++
  "    void  (*set_reg)(void* ctx, uint32_t reg_idx, uint64_t val);\n" ++
  "    uint64_t (*get_reg)(void* ctx, uint32_t reg_idx);\n" ++
  "    const char* (*reg_name)(uint32_t idx);\n" ++
  "    uint32_t (*num_regs)(void);\n" ++
  "    void* (*snapshot)(void* ctx);\n" ++
  "    void  (*restore)(void* ctx, void* snap);\n" ++
  "    void  (*free_snapshot)(void* snap);\n" ++
  "} JitVTable;\n\n" ++
  "static uint64_t v_get_wire(void*, uint32_t) { return 0; }\n" ++
  "static void v_set_mem(void*, uint32_t, uint32_t, uint32_t) {}\n" ++
  "static uint32_t v_get_mem(void*, uint32_t, uint32_t) { return 0; }\n" ++
  "static void v_memset_word(void*, uint32_t, uint32_t, uint32_t, uint32_t) {}\n" ++
  "static const char* v_name(uint32_t) { return \"\"; }\n" ++
  "static uint32_t v_zero(void) { return 0; }\n" ++
  "static void v_set_reg(void*, uint32_t, uint64_t) {}\n" ++
  "static uint64_t v_get_reg(void*, uint32_t) { return 0; }\n" ++
  "static void* v_snapshot(void*) { return nullptr; }\n" ++
  "static void v_restore(void*, void*) {}\n" ++
  "static void v_free_snapshot(void*) {}\n\n" ++
  "static const JitVTable g_sparkle_verilator_vtable = {\n" ++
  "    jit_create, jit_destroy, jit_reset, jit_eval, jit_tick, jit_eval_tick,\n" ++
  "    jit_set_input, jit_get_output, v_get_wire, v_set_mem, v_get_mem, v_memset_word,\n" ++
  "    v_name, v_zero, v_set_reg, v_get_reg, v_name, v_zero,\n" ++
  "    v_snapshot, v_restore, v_free_snapshot\n" ++
  "};\n\n" ++
  "__attribute__((visibility(\"default\")))\n" ++
  "const JitVTable* jit_vtable(void) { return &g_sparkle_verilator_vtable; }\n\n" ++
  "} // extern \"C\"\n"

/-- Run Verilator on `sources` together with the wrapper `tb`, link the
    result into a shared object in `objDir`, and load it.  `sources` should
    be absolute paths: Verilator records them in the makefile it then runs
    with `make -C <objDir>`. -/
def buildAndLoad (top : String) (sources : List String) (tb : String) (objDir : String)
    (verilatorArgs : List String := []) : IO JITHandle := do
  IO.FS.createDirAll objDir
  let tbPath := s!"{objDir}/sparkle_verilator_tb.cpp"
  IO.FS.writeFile tbPath tb
  let soPath := s!"{objDir}/V{top}.so"
  let r ← IO.Process.output {
    cmd := "verilator"
    args := #["--cc", "--build", "-j", "0", "--top-module", top,
              "-CFLAGS", "-O2 -fPIC", "--Mdir", objDir]
            ++ verilatorArgs.toArray ++ sources.toArray ++ #[tbPath]
    stdin := .null
  }
  if r.exitCode != 0 then
    throw (IO.userError s!"verilator build failed (exit {r.exitCode}):\n{r.stderr}")
  -- `verilator --cc --build` (no `--exe`) stops at static libraries — the
  -- model plus the wrapper in `libV<top>.a`, the runtime in
  -- `libverilated.a` — and never links.  Link the shared object here,
  -- every time: the libraries may just have been rebuilt.
  let cxx := (← IO.getEnv "CXX").getD "c++"
  let l ← IO.Process.output {
    cmd := cxx
    args := #["-shared", "-o", soPath,
              "-Wl,--whole-archive", s!"{objDir}/libV{top}.a", "-Wl,--no-whole-archive",
              s!"{objDir}/libverilated.a", "-pthread"]
    stdin := .null }
  if l.exitCode != 0 then
    throw (IO.userError s!"linking {soPath} failed (exit {l.exitCode}):\n{l.stderr}")
  JIT.load soPath

/-- Build a Verilator-backed `.so` from a Sparkle-generated `.sv`,
    then load it via the existing JIT FFI.

    - `svPath` — path to a `.sv` written by, e.g.,
      `Sparkle.Backend.Verilog.writeVerilogFile`.
    - `top`    — top-module name (matches what's in the `.sv`).
    - `inputs` / `outputs` — port lists *excluding* `clk` / `rst`
      (matching the JIT's `jit_set_input` / `jit_get_output`
      indexing).
    - `objDir` — temp directory for Verilator artefacts.

    Returns a `Simulator` whose `handle` is opened against the
    just-built `.so`. -/
def of (svPath top : String) (inputs outputs : List PortSpec)
    (objDir : String := "/tmp/sparkle_verilator") : IO Simulator := do
  -- `top` may be the Lean name (`Foo.Bar.baz`, what `#sim` passes); the
  -- module in the `.sv` and its ports carry the Verilog backend's
  -- spelling (`Sparkle.Backend.Verilog.sanitizeName`).
  let verilogName (n : String) : String :=
    if n.all (fun c => c.isAlphanum || c == '_' || c == '$') then n
    else n.replace "." "_" |>.replace "-" "_" |>.replace " " "_"
          |>.replace "'" "_prime" |>.replace "#" ""
  let top := verilogName top
  let inputs := inputs.map fun p => { p with name := verilogName p.name }
  let outputs := outputs.map fun p => { p with name := verilogName p.name }
  -- one build directory per design: a second design must not reuse the
  -- first one's generated sources
  let objDir := s!"{objDir}/{top}"
  IO.FS.createDirAll objDir
  -- Absolute: Verilator records the source path in the makefile it then
  -- runs with `make -C <objDir>`; a relative path is not found from there
  -- when the directory is reused, and the second build fails.
  let svPath := (← IO.FS.realPath svPath).toString
  let handle ← buildAndLoad top [svPath] (emitTb top inputs outputs) objDir
    ["-Wno-WIDTHEXPAND", "-Wno-WIDTHTRUNC", "-Wno-UNUSEDSIGNAL", "-Wno-CASEINCOMPLETE"]
  pure { handle := handle }

instance : Sparkle.Core.Sim.Sim Simulator
    (List (UInt32 × UInt64))    -- raw (port-index, value) drives
    (UInt32 → IO UInt64)        -- a getter you call per cycle
    where
  reset sim := JIT.reset sim.handle
  step sim drives := do
    for (idx, val) in drives do
      JIT.setInput sim.handle idx val
    JIT.evalTick sim.handle
  read sim := pure (fun idx => JIT.getOutput sim.handle idx)
  destroy sim := JIT.destroy sim.handle

end Sparkle.Core.Sim.Verilator
