#==============================================================================
# Sparkle → Alveo U280 Vivado Build Script (STUB)
#
# This file is a commented-out placeholder showing the intended shape of
# the Vivado synthesis / place-and-route / bitstream-generation flow for
# Sparkle-generated RTL on the Alveo U280.
#
# IT IS NOT YET RUNNABLE. See fpga/U280/README.md for the list of
# missing pieces (PCIe shell, HBM controller, clock wizard, reset
# synchronizer, constraints.xdc pin assignments, etc.).
#
# When those are all in place, this script is intended to be invoked by
# running, from the repo root:
#
#     vivado -mode batch -source fpga/U280/build.tcl
#
# Or in non-project mode for CI:
#
#     vivado -mode tcl -source fpga/U280/build.tcl
#==============================================================================

puts "========================================================================"
puts "  Sparkle U280 build.tcl — STUB"
puts "  See fpga/U280/README.md for the list of missing pieces."
puts "========================================================================"

# --- Target device ----------------------------------------------------
# set part   xcu280-fsvh2892-2L-e
# set board  xilinx.com:au280:part0:1.2

# --- Project setup (non-project mode) --------------------------------
# create_project -in_memory -part $part
# set_property board_part $board [current_project]

# --- RTL ingest -------------------------------------------------------
# The Sparkle SoC is generated by `lake build IP.RV32.SoCVerilog` and
# lands in verilator/generated_soc.sv. Add it here alongside any
# Verilog wrappers (rv32i_soc_wrapper.sv etc.).
#
# read_verilog -sv [list \
#     ../../verilator/generated_soc.sv \
#     ../../verilator/rv32i_soc_wrapper.sv ]

# --- Xilinx IP -------------------------------------------------------
# These .xci files do not exist yet. They must be generated via IP
# Catalog (GUI) or the Tcl `create_ip` commands when Level 1b begins.
#
# read_ip [list \
#     ip/pcie4c_uscale_plus_0/pcie4c_uscale_plus_0.xci \
#     ip/hbm_0/hbm_0.xci                              \
#     ip/clk_wiz_0/clk_wiz_0.xci ]
# upgrade_ip [get_ips]
# generate_target all [get_ips]
# synth_ip     [get_ips]

# --- Constraints -----------------------------------------------------
# read_xdc constraints.xdc

# --- Synthesis -------------------------------------------------------
# synth_design -top rv32iSoCSynth -part $part

# --- Implementation --------------------------------------------------
# opt_design
# place_design
# phys_opt_design
# route_design
# phys_opt_design -directive AggressiveExplore

# --- Reports ---------------------------------------------------------
# report_timing_summary  -file reports/timing_summary.rpt
# report_utilization     -file reports/utilization.rpt
# report_power           -file reports/power.rpt
# report_drc             -file reports/drc.rpt

# --- Bitstream -------------------------------------------------------
# write_bitstream -force build/sparkle_u280.bit
# write_cfgmem   -force -format MCS -interface SPIX8  \
#                -size 256 -loadbit "up 0 build/sparkle_u280.bit" \
#                build/sparkle_u280.mcs

# --- For Vitis (.xclbin) path ----------------------------------------
# package_xclbin -out build/sparkle_u280.xclbin  \
#                -xsa_file build/sparkle_u280.xsa

puts "========================================================================"
puts "  STUB complete — no real work was done."
puts "  Re-read fpga/U280/README.md for the roadmap."
puts "========================================================================"
