#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

cd "$repo_root"
generated_sv="$work_dir/symbolic_parameters.sv"
lake env lean Tests/SymbolicParameterEmit.lean 2>&1 | awk '
  /^\/\/ Generated by Sparkle HDL$/ { emitting = 1 }
  emitting { print }
  /^endmodule$/ { emitting = 0 }
' > "$generated_sv"

for width in 3 17 65; do
  simulation="$work_dir/symbolic_xor_w${width}"
  iverilog -g2012 \
    -DTEST_WIDTH="$width" \
    -s tb \
    -o "$simulation" \
    "$generated_sv" \
    Tests/Fixtures/symbolic_xor_tb.sv
  vvp "$simulation"
done

behavior_simulation="$work_dir/symbolic_parameter_behavior"
iverilog -g2012 \
  -s symbolic_parameter_behavior_tb \
  -o "$behavior_simulation" \
  "$generated_sv" \
  Tests/SymbolicParameterBehavior.sv
vvp "$behavior_simulation"
