`timescale 1ns / 1ps
// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : sim.v
// Top        : SimSoC
// Device     : SIM
// Hierarchy  : disabled
// LiteX sha1 : 013443b
// Date       : 2026-03-26 14:47:40
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module sim_core (
    input  wire    [7:0] serial_sink_data,
    output wire          serial_sink_ready,
    input  wire          serial_sink_valid,
    output wire    [7:0] serial_source_data,
    input  wire          serial_source_ready,
    output wire          serial_source_valid,
    output wire          sim_trace,
    input  wire          sys_clk
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------

/*
SimSoC
├── crg (CRG)
├── bus (SoCBusHandler)
│    └── _interconnect (InterconnectShared)
│         ├── arbiter (Arbiter)
│         │    └── rr (RoundRobin)
│         ├── decoder (Decoder)
│         └── timeout (Timeout)
│              └── waittimer_0 (WaitTimer) [Gen]
├── csr (SoCCSRHandler)
├── irq (SoCIRQHandler)
├── ctrl (SoCController)
├── cpu (PicoRV32)
│    └── [BB:picorv32]
├── rom (SRAM)
├── sram (SRAM)
├── main_ram (SRAM)
├── identifier (Identifier)
├── uart (UART)
│    ├── ev (EventManager)
│    │    ├── eventsourcelevel_0 (EventSourceLevel) [Gen]
│    │    └── eventsourcelevel_1 (EventSourceLevel) [Gen]
│    ├── phy (RS232PHYModel)
│    ├── tx_fifo (SyncFIFO)
│    │    └── fifo (SyncFIFOBuffered)
│    │         └── fifo (SyncFIFO)
│    └── rx_fifo (SyncFIFO)
│         └── fifo (SyncFIFOBuffered)
│              └── fifo (SyncFIFO)
├── timer0 (Timer)
│    └── ev (EventManager)
│         └── eventsourceprocess_0 (EventSourceProcess) [Gen]
├── csr_bridge (Wishbone2CSR)
│    └── fsm (FSM)
├── csr_bankarray (CSRBankArray)
│    ├── csrbank_0 (CSRBank) [Gen]
│    │    ├── csrstorage_0 (CSRStorage) [Gen]
│    │    ├── csrstorage_1 (CSRStorage) [Gen]
│    │    └── csrstatus_0 (CSRStatus) [Gen]
│    ├── sram_0 (SRAM) [Gen]
│    ├── csrbank_1 (CSRBank) [Gen]
│    │    ├── csrstorage_0 (CSRStorage) [Gen]
│    │    ├── csrstorage_1 (CSRStorage) [Gen]
│    │    ├── csrstorage_2 (CSRStorage) [Gen]
│    │    ├── csrstorage_3 (CSRStorage) [Gen]
│    │    ├── csrstatus_0 (CSRStatus) [Gen]
│    │    ├── csrstatus_1 (CSRStatus) [Gen]
│    │    ├── csrstatus_2 (CSRStatus) [Gen]
│    │    └── csrstorage_4 (CSRStorage) [Gen]
│    └── csrbank_2 (CSRBank) [Gen]
│         ├── csrstatus_0 (CSRStatus) [Gen]
│         ├── csrstatus_1 (CSRStatus) [Gen]
│         ├── csrstatus_2 (CSRStatus) [Gen]
│         ├── csrstatus_3 (CSRStatus) [Gen]
│         ├── csrstorage_0 (CSRStorage) [Gen]
│         ├── csrstatus_4 (CSRStatus) [Gen]
│         └── csrstatus_5 (CSRStatus) [Gen]
└── csr_interconnect (InterconnectShared)
Legend:
  [Gen]: Auto-generated instance name.
  [BB:NAME]: Blackbox instance (verilog Instance).

*/

//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire          adapted_interface_ack;
wire   [29:0] adapted_interface_adr;
wire    [1:0] adapted_interface_bte;
wire    [2:0] adapted_interface_cti;
wire          adapted_interface_cyc;
wire   [31:0] adapted_interface_dat_r;
wire   [31:0] adapted_interface_dat_w;
wire          adapted_interface_err;
wire    [3:0] adapted_interface_sel;
wire          adapted_interface_stb;
wire          adapted_interface_we;
wire   [14:0] adr;
reg           adr_burst = 1'd0;
reg    [29:0] array_muxed0 = 30'd0;
reg    [31:0] array_muxed1 = 32'd0;
reg     [3:0] array_muxed2 = 4'd0;
reg           array_muxed3 = 1'd0;
reg           array_muxed4 = 1'd0;
reg           array_muxed5 = 1'd0;
reg     [2:0] array_muxed6 = 3'd0;
reg     [1:0] array_muxed7 = 2'd0;
wire          bus_error;
reg    [31:0] bus_errors = 32'd0;
reg           bus_errors_re = 1'd0;
wire   [31:0] bus_errors_status;
wire          bus_errors_we;
reg    [19:0] count = 20'd1000000;
reg           crg_int_rst = 1'd1;
wire    [5:0] csr_bankarray_adr;
wire          csr_bankarray_csrbank0_sel;
wire   [31:0] csr_bankarray_csrbank0_sel_bus_errors_r;
reg           csr_bankarray_csrbank0_sel_bus_errors_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank0_sel_bus_errors_w;
reg           csr_bankarray_csrbank0_sel_bus_errors_we = 1'd0;
wire    [1:0] csr_bankarray_csrbank0_sel_reset0_r;
reg           csr_bankarray_csrbank0_sel_reset0_re = 1'd0;
wire    [1:0] csr_bankarray_csrbank0_sel_reset0_w;
reg           csr_bankarray_csrbank0_sel_reset0_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank0_sel_scratch0_r;
reg           csr_bankarray_csrbank0_sel_scratch0_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank0_sel_scratch0_w;
reg           csr_bankarray_csrbank0_sel_scratch0_we = 1'd0;
wire          csr_bankarray_csrbank1_sel;
wire          csr_bankarray_csrbank1_sel_en0_r;
reg           csr_bankarray_csrbank1_sel_en0_re = 1'd0;
wire          csr_bankarray_csrbank1_sel_en0_w;
reg           csr_bankarray_csrbank1_sel_en0_we = 1'd0;
wire          csr_bankarray_csrbank1_sel_ev_enable0_r;
reg           csr_bankarray_csrbank1_sel_ev_enable0_re = 1'd0;
wire          csr_bankarray_csrbank1_sel_ev_enable0_w;
reg           csr_bankarray_csrbank1_sel_ev_enable0_we = 1'd0;
wire          csr_bankarray_csrbank1_sel_ev_pending_r;
reg           csr_bankarray_csrbank1_sel_ev_pending_re = 1'd0;
wire          csr_bankarray_csrbank1_sel_ev_pending_w;
reg           csr_bankarray_csrbank1_sel_ev_pending_we = 1'd0;
wire          csr_bankarray_csrbank1_sel_ev_status_r;
reg           csr_bankarray_csrbank1_sel_ev_status_re = 1'd0;
wire          csr_bankarray_csrbank1_sel_ev_status_w;
reg           csr_bankarray_csrbank1_sel_ev_status_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_sel_load0_r;
reg           csr_bankarray_csrbank1_sel_load0_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_sel_load0_w;
reg           csr_bankarray_csrbank1_sel_load0_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_sel_reload0_r;
reg           csr_bankarray_csrbank1_sel_reload0_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_sel_reload0_w;
reg           csr_bankarray_csrbank1_sel_reload0_we = 1'd0;
wire          csr_bankarray_csrbank1_sel_update_value0_r;
reg           csr_bankarray_csrbank1_sel_update_value0_re = 1'd0;
wire          csr_bankarray_csrbank1_sel_update_value0_w;
reg           csr_bankarray_csrbank1_sel_update_value0_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_sel_value_r;
reg           csr_bankarray_csrbank1_sel_value_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_sel_value_w;
reg           csr_bankarray_csrbank1_sel_value_we = 1'd0;
wire          csr_bankarray_csrbank2_sel;
wire    [1:0] csr_bankarray_csrbank2_sel_ev_enable0_r;
reg           csr_bankarray_csrbank2_sel_ev_enable0_re = 1'd0;
wire    [1:0] csr_bankarray_csrbank2_sel_ev_enable0_w;
reg           csr_bankarray_csrbank2_sel_ev_enable0_we = 1'd0;
wire    [1:0] csr_bankarray_csrbank2_sel_ev_pending_r;
reg           csr_bankarray_csrbank2_sel_ev_pending_re = 1'd0;
wire    [1:0] csr_bankarray_csrbank2_sel_ev_pending_w;
reg           csr_bankarray_csrbank2_sel_ev_pending_we = 1'd0;
wire    [1:0] csr_bankarray_csrbank2_sel_ev_status_r;
reg           csr_bankarray_csrbank2_sel_ev_status_re = 1'd0;
wire    [1:0] csr_bankarray_csrbank2_sel_ev_status_w;
reg           csr_bankarray_csrbank2_sel_ev_status_we = 1'd0;
wire          csr_bankarray_csrbank2_sel_rxempty_r;
reg           csr_bankarray_csrbank2_sel_rxempty_re = 1'd0;
wire          csr_bankarray_csrbank2_sel_rxempty_w;
reg           csr_bankarray_csrbank2_sel_rxempty_we = 1'd0;
wire          csr_bankarray_csrbank2_sel_rxfull_r;
reg           csr_bankarray_csrbank2_sel_rxfull_re = 1'd0;
wire          csr_bankarray_csrbank2_sel_rxfull_w;
reg           csr_bankarray_csrbank2_sel_rxfull_we = 1'd0;
wire          csr_bankarray_csrbank2_sel_txempty_r;
reg           csr_bankarray_csrbank2_sel_txempty_re = 1'd0;
wire          csr_bankarray_csrbank2_sel_txempty_w;
reg           csr_bankarray_csrbank2_sel_txempty_we = 1'd0;
wire          csr_bankarray_csrbank2_sel_txfull_r;
reg           csr_bankarray_csrbank2_sel_txfull_re = 1'd0;
wire          csr_bankarray_csrbank2_sel_txfull_w;
reg           csr_bankarray_csrbank2_sel_txfull_we = 1'd0;
wire    [7:0] csr_bankarray_dat_r;
wire   [13:0] csr_bankarray_interface0_bank_bus_adr;
reg    [31:0] csr_bankarray_interface0_bank_bus_dat_r = 32'd0;
wire   [31:0] csr_bankarray_interface0_bank_bus_dat_w;
wire          csr_bankarray_interface0_bank_bus_re;
wire          csr_bankarray_interface0_bank_bus_we;
wire   [13:0] csr_bankarray_interface1_bank_bus_adr;
reg    [31:0] csr_bankarray_interface1_bank_bus_dat_r = 32'd0;
wire   [31:0] csr_bankarray_interface1_bank_bus_dat_w;
wire          csr_bankarray_interface1_bank_bus_re;
wire          csr_bankarray_interface1_bank_bus_we;
wire   [13:0] csr_bankarray_interface2_bank_bus_adr;
reg    [31:0] csr_bankarray_interface2_bank_bus_dat_r = 32'd0;
wire   [31:0] csr_bankarray_interface2_bank_bus_dat_w;
wire          csr_bankarray_interface2_bank_bus_re;
wire          csr_bankarray_interface2_bank_bus_we;
wire          csr_bankarray_sel;
reg           csr_bankarray_sel_r = 1'd0;
wire   [13:0] csr_bankarray_sram_bus_adr;
reg    [31:0] csr_bankarray_sram_bus_dat_r = 32'd0;
wire   [31:0] csr_bankarray_sram_bus_dat_w;
wire          csr_bankarray_sram_bus_re;
wire          csr_bankarray_sram_bus_we;
wire   [13:0] csr_interconnect_adr;
wire   [31:0] csr_interconnect_dat_r;
wire   [31:0] csr_interconnect_dat_w;
wire          csr_interconnect_re;
wire          csr_interconnect_we;
wire   [31:0] dat_r;
wire          done;
reg           error = 1'd0;
wire          grant;
reg           interface0_ram_bus_ack = 1'd0;
wire   [29:0] interface0_ram_bus_adr;
wire    [1:0] interface0_ram_bus_bte;
wire    [2:0] interface0_ram_bus_cti;
wire          interface0_ram_bus_cyc;
wire   [31:0] interface0_ram_bus_dat_r;
wire   [31:0] interface0_ram_bus_dat_w;
reg           interface0_ram_bus_err = 1'd0;
wire    [3:0] interface0_ram_bus_sel;
wire          interface0_ram_bus_stb;
wire          interface0_ram_bus_we;
reg           interface1_ram_bus_ack = 1'd0;
wire   [29:0] interface1_ram_bus_adr;
wire    [1:0] interface1_ram_bus_bte;
wire    [2:0] interface1_ram_bus_cti;
wire          interface1_ram_bus_cyc;
wire   [31:0] interface1_ram_bus_dat_r;
wire   [31:0] interface1_ram_bus_dat_w;
reg           interface1_ram_bus_err = 1'd0;
wire    [3:0] interface1_ram_bus_sel;
wire          interface1_ram_bus_stb;
wire          interface1_ram_bus_we;
wire          picorv320;
wire          picorv321;
wire   [31:0] picorv322;
wire   [31:0] picorv323;
wire    [3:0] picorv324;
wire          picorv325;
wire   [31:0] picorv326;
wire   [31:0] picorv327;
wire   [31:0] picorv328;
wire   [31:0] picorv329;
wire          picorv32_idbus_ack;
wire   [31:0] picorv32_idbus_adr;
wire    [1:0] picorv32_idbus_bte;
wire    [2:0] picorv32_idbus_cti;
wire          picorv32_idbus_cyc;
wire   [31:0] picorv32_idbus_dat_r;
wire   [31:0] picorv32_idbus_dat_w;
wire          picorv32_idbus_err;
reg     [3:0] picorv32_idbus_sel = 4'd0;
wire          picorv32_idbus_stb;
reg           picorv32_idbus_we = 1'd0;
reg    [31:0] picorv32_interrupt = 32'd0;
wire   [31:0] picorv32_mem_addr;
wire          picorv32_mem_instr;
wire   [31:0] picorv32_mem_rdata;
wire          picorv32_mem_ready;
wire          picorv32_mem_valid;
wire   [31:0] picorv32_mem_wdata;
wire    [3:0] picorv32_mem_wstrb;
wire          picorv32_reset;
wire          picorv32_trap;
wire          por_clk;
reg           ram_bus_ack = 1'd0;
wire   [29:0] ram_bus_adr;
wire    [1:0] ram_bus_bte;
wire    [2:0] ram_bus_cti;
wire          ram_bus_cyc;
wire   [31:0] ram_bus_dat_r;
wire   [31:0] ram_bus_dat_w;
reg           ram_bus_err = 1'd0;
wire    [3:0] ram_bus_sel;
wire          ram_bus_stb;
wire          ram_bus_we;
wire          request;
wire          reset_cpu_rst;
reg           reset_re = 1'd0;
reg     [1:0] reset_storage = 2'd0;
reg           scratch_re = 1'd0;
reg    [31:0] scratch_storage = 32'd305419896;
reg           shared_ack = 1'd0;
wire   [29:0] shared_adr;
wire    [1:0] shared_bte;
wire    [2:0] shared_cti;
wire          shared_cyc;
reg    [31:0] shared_dat_r = 32'd0;
wire   [31:0] shared_dat_w;
wire          shared_err;
wire    [3:0] shared_sel;
wire          shared_stb;
wire          shared_we;
reg           simsoc_ack = 1'd0;
wire   [29:0] simsoc_adr;
wire    [1:0] simsoc_bte;
reg    [13:0] simsoc_csr_bridge_adr = 14'd0;
wire   [31:0] simsoc_csr_bridge_dat_r;
reg    [31:0] simsoc_csr_bridge_dat_w = 32'd0;
reg           simsoc_csr_bridge_re = 1'd0;
reg           simsoc_csr_bridge_we = 1'd0;
wire    [2:0] simsoc_cti;
wire          simsoc_cyc;
reg    [31:0] simsoc_dat_r = 32'd0;
wire   [31:0] simsoc_dat_w;
reg           simsoc_err = 1'd0;
reg           simsoc_next_state = 1'd0;
wire    [3:0] simsoc_sel;
reg           simsoc_state = 1'd0;
wire          simsoc_stb;
wire          simsoc_we;
wire          sink_first;
wire          sink_last;
wire    [7:0] sink_payload_data;
wire          sink_ready;
wire          sink_valid;
reg     [3:0] slave_sel = 4'd0;
reg     [3:0] slave_sel_r = 4'd0;
reg           soc_rst = 1'd0;
reg           source_first = 1'd0;
reg           source_last = 1'd0;
wire    [7:0] source_payload_data;
wire          source_ready;
wire          source_valid;
wire   [10:0] sram0_adr;
reg           sram0_adr_burst = 1'd0;
wire   [31:0] sram0_dat_r;
wire   [31:0] sram0_dat_w;
reg     [3:0] sram0_we = 4'd0;
wire   [13:0] sram1_adr;
reg           sram1_adr_burst = 1'd0;
wire   [31:0] sram1_dat_r;
wire   [31:0] sram1_dat_w;
reg     [3:0] sram1_we = 4'd0;
wire          sys_clk_1;
wire          sys_rst;
reg           timer_en_re = 1'd0;
reg           timer_en_storage = 1'd0;
wire          timer_irq;
reg           timer_load_re = 1'd0;
reg    [31:0] timer_load_storage = 32'd0;
reg           timer_reload_re = 1'd0;
reg    [31:0] timer_reload_storage = 32'd0;
reg           timer_update_value_re = 1'd0;
reg           timer_update_value_storage = 1'd0;
reg    [31:0] timer_value = 32'd0;
reg           timer_value_enable_re = 1'd0;
reg           timer_value_enable_storage = 1'd0;
reg           timer_value_pending_r = 1'd0;
reg           timer_value_pending_re = 1'd0;
wire          timer_value_pending_status;
wire          timer_value_pending_we;
reg           timer_value_re = 1'd0;
reg    [31:0] timer_value_status = 32'd0;
reg           timer_value_status_re = 1'd0;
wire          timer_value_status_status;
wire          timer_value_status_we;
wire          timer_value_we;
wire          timer_value_zero0;
wire          timer_value_zero1;
wire          timer_value_zero2;
reg           timer_zero_clear = 1'd0;
reg           timer_zero_pending = 1'd0;
wire          timer_zero_status;
wire          timer_zero_trigger;
reg           timer_zero_trigger_d = 1'd0;
wire          uart_irq;
wire          uart_phy_sink_first;
wire          uart_phy_sink_last;
wire    [7:0] uart_phy_sink_payload_data;
wire          uart_phy_sink_ready;
wire          uart_phy_sink_valid;
wire          uart_phy_source_first;
wire          uart_phy_source_last;
wire    [7:0] uart_phy_source_payload_data;
wire          uart_phy_source_ready;
wire          uart_phy_source_valid;
reg           uart_rx_clear = 1'd0;
reg     [3:0] uart_rx_fifo_consume = 4'd0;
wire          uart_rx_fifo_do_read;
wire          uart_rx_fifo_fifo_in_first;
wire          uart_rx_fifo_fifo_in_last;
wire    [7:0] uart_rx_fifo_fifo_in_payload_data;
wire          uart_rx_fifo_fifo_out_first;
wire          uart_rx_fifo_fifo_out_last;
wire    [7:0] uart_rx_fifo_fifo_out_payload_data;
reg     [4:0] uart_rx_fifo_level0 = 5'd0;
wire    [4:0] uart_rx_fifo_level1;
wire    [9:0] uart_rx_fifo_level_din;
wire    [9:0] uart_rx_fifo_level_dout;
wire          uart_rx_fifo_level_re;
wire          uart_rx_fifo_level_readable;
wire          uart_rx_fifo_level_we;
wire          uart_rx_fifo_level_writable;
reg     [3:0] uart_rx_fifo_produce = 4'd0;
wire    [3:0] uart_rx_fifo_rdport_adr;
wire    [9:0] uart_rx_fifo_rdport_dat_r;
wire          uart_rx_fifo_rdport_re;
wire          uart_rx_fifo_re;
reg           uart_rx_fifo_readable = 1'd0;
reg           uart_rx_fifo_replace = 1'd0;
wire          uart_rx_fifo_sink_first;
wire          uart_rx_fifo_sink_last;
wire    [7:0] uart_rx_fifo_sink_payload_data;
wire          uart_rx_fifo_sink_ready;
wire          uart_rx_fifo_sink_valid;
wire          uart_rx_fifo_source_first;
wire          uart_rx_fifo_source_last;
wire    [7:0] uart_rx_fifo_source_payload_data;
wire          uart_rx_fifo_source_ready;
wire          uart_rx_fifo_source_valid;
reg     [3:0] uart_rx_fifo_wrport_adr = 4'd0;
wire    [9:0] uart_rx_fifo_wrport_dat_r;
wire    [9:0] uart_rx_fifo_wrport_dat_w;
wire          uart_rx_fifo_wrport_we;
wire          uart_rx_pending;
wire          uart_rx_status;
wire          uart_rx_trigger;
reg           uart_rxempty_re = 1'd0;
wire          uart_rxempty_status;
wire          uart_rxempty_we;
reg           uart_rxfull_re = 1'd0;
wire          uart_rxfull_status;
wire          uart_rxfull_we;
wire    [7:0] uart_rxtx_r;
reg           uart_rxtx_re = 1'd0;
wire    [7:0] uart_rxtx_w;
reg           uart_rxtx_we = 1'd0;
reg           uart_tx_clear = 1'd0;
reg     [3:0] uart_tx_fifo_consume = 4'd0;
wire          uart_tx_fifo_do_read;
wire          uart_tx_fifo_fifo_in_first;
wire          uart_tx_fifo_fifo_in_last;
wire    [7:0] uart_tx_fifo_fifo_in_payload_data;
wire          uart_tx_fifo_fifo_out_first;
wire          uart_tx_fifo_fifo_out_last;
wire    [7:0] uart_tx_fifo_fifo_out_payload_data;
reg     [4:0] uart_tx_fifo_level0 = 5'd0;
wire    [4:0] uart_tx_fifo_level1;
wire    [9:0] uart_tx_fifo_level_din;
wire    [9:0] uart_tx_fifo_level_dout;
wire          uart_tx_fifo_level_re;
wire          uart_tx_fifo_level_readable;
wire          uart_tx_fifo_level_we;
wire          uart_tx_fifo_level_writable;
reg     [3:0] uart_tx_fifo_produce = 4'd0;
wire    [3:0] uart_tx_fifo_rdport_adr;
wire    [9:0] uart_tx_fifo_rdport_dat_r;
wire          uart_tx_fifo_rdport_re;
wire          uart_tx_fifo_re;
reg           uart_tx_fifo_readable = 1'd0;
reg           uart_tx_fifo_replace = 1'd0;
reg           uart_tx_fifo_sink_first = 1'd0;
reg           uart_tx_fifo_sink_last = 1'd0;
wire    [7:0] uart_tx_fifo_sink_payload_data;
wire          uart_tx_fifo_sink_ready;
wire          uart_tx_fifo_sink_valid;
wire          uart_tx_fifo_source_first;
wire          uart_tx_fifo_source_last;
wire    [7:0] uart_tx_fifo_source_payload_data;
wire          uart_tx_fifo_source_ready;
wire          uart_tx_fifo_source_valid;
reg     [3:0] uart_tx_fifo_wrport_adr = 4'd0;
wire    [9:0] uart_tx_fifo_wrport_dat_r;
wire    [9:0] uart_tx_fifo_wrport_dat_w;
wire          uart_tx_fifo_wrport_we;
wire          uart_tx_pending;
wire          uart_tx_status;
wire          uart_tx_trigger;
reg           uart_txempty_enable_re = 1'd0;
reg     [1:0] uart_txempty_enable_storage = 2'd0;
reg     [1:0] uart_txempty_pending_r = 2'd0;
reg           uart_txempty_pending_re = 1'd0;
reg     [1:0] uart_txempty_pending_status = 2'd0;
wire          uart_txempty_pending_we;
reg           uart_txempty_re = 1'd0;
wire          uart_txempty_rx0;
wire          uart_txempty_rx1;
wire          uart_txempty_rx2;
wire          uart_txempty_status;
reg           uart_txempty_status_re = 1'd0;
reg     [1:0] uart_txempty_status_status = 2'd0;
wire          uart_txempty_status_we;
wire          uart_txempty_tx0;
wire          uart_txempty_tx1;
wire          uart_txempty_tx2;
wire          uart_txempty_we;
reg           uart_txfull_re = 1'd0;
wire          uart_txfull_status;
wire          uart_txfull_we;
wire          wait_1;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign picorv32_reset = (soc_rst | reset_cpu_rst);
assign sim_trace = 1'd1;
assign bus_error = error;
always @(*) begin
    picorv32_interrupt <= 32'd0;
    picorv32_interrupt[4] <= timer_irq;
    picorv32_interrupt[3] <= uart_irq;
end
assign sys_clk_1 = sys_clk;
assign por_clk = sys_clk;
assign sys_rst = crg_int_rst;
assign adapted_interface_dat_w = picorv32_idbus_dat_w;
assign picorv32_idbus_dat_r = adapted_interface_dat_r;
assign adapted_interface_sel = picorv32_idbus_sel;
assign adapted_interface_cyc = picorv32_idbus_cyc;
assign adapted_interface_stb = picorv32_idbus_stb;
assign picorv32_idbus_ack = adapted_interface_ack;
assign adapted_interface_we = picorv32_idbus_we;
assign adapted_interface_cti = picorv32_idbus_cti;
assign adapted_interface_bte = picorv32_idbus_bte;
assign picorv32_idbus_err = adapted_interface_err;
assign adapted_interface_adr = picorv32_idbus_adr[31:2];
assign shared_adr = array_muxed0;
assign shared_dat_w = array_muxed1;
assign shared_sel = array_muxed2;
assign shared_cyc = array_muxed3;
assign shared_stb = array_muxed4;
assign shared_we = array_muxed5;
assign shared_cti = array_muxed6;
assign shared_bte = array_muxed7;
assign adapted_interface_dat_r = shared_dat_r;
assign adapted_interface_ack = (shared_ack & (grant == 1'd0));
assign adapted_interface_err = (shared_err & (grant == 1'd0));
assign request = {adapted_interface_cyc};
assign grant = 1'd0;
always @(*) begin
    slave_sel <= 4'd0;
    slave_sel[0] <= (shared_adr[29:15] == 1'd0);
    slave_sel[1] <= (shared_adr[29:11] == 12'd2048);
    slave_sel[2] <= (shared_adr[29:14] == 15'd16384);
    slave_sel[3] <= (shared_adr[29:14] == 16'd33280);
end
assign ram_bus_adr = shared_adr;
assign ram_bus_dat_w = shared_dat_w;
assign ram_bus_sel = shared_sel;
assign ram_bus_stb = shared_stb;
assign ram_bus_we = shared_we;
assign ram_bus_cti = shared_cti;
assign ram_bus_bte = shared_bte;
assign interface0_ram_bus_adr = shared_adr;
assign interface0_ram_bus_dat_w = shared_dat_w;
assign interface0_ram_bus_sel = shared_sel;
assign interface0_ram_bus_stb = shared_stb;
assign interface0_ram_bus_we = shared_we;
assign interface0_ram_bus_cti = shared_cti;
assign interface0_ram_bus_bte = shared_bte;
assign interface1_ram_bus_adr = shared_adr;
assign interface1_ram_bus_dat_w = shared_dat_w;
assign interface1_ram_bus_sel = shared_sel;
assign interface1_ram_bus_stb = shared_stb;
assign interface1_ram_bus_we = shared_we;
assign interface1_ram_bus_cti = shared_cti;
assign interface1_ram_bus_bte = shared_bte;
assign simsoc_adr = shared_adr;
assign simsoc_dat_w = shared_dat_w;
assign simsoc_sel = shared_sel;
assign simsoc_stb = shared_stb;
assign simsoc_we = shared_we;
assign simsoc_cti = shared_cti;
assign simsoc_bte = shared_bte;
assign ram_bus_cyc = (shared_cyc & slave_sel[0]);
assign interface0_ram_bus_cyc = (shared_cyc & slave_sel[1]);
assign interface1_ram_bus_cyc = (shared_cyc & slave_sel[2]);
assign simsoc_cyc = (shared_cyc & slave_sel[3]);
always @(*) begin
    shared_ack <= 1'd0;
    shared_ack <= (((ram_bus_ack | interface0_ram_bus_ack) | interface1_ram_bus_ack) | simsoc_ack);
    if (done) begin
        shared_ack <= 1'd1;
    end
end
assign shared_err = (((ram_bus_err | interface0_ram_bus_err) | interface1_ram_bus_err) | simsoc_err);
always @(*) begin
    shared_dat_r <= 32'd0;
    shared_dat_r <= (((({32{slave_sel_r[0]}} & ram_bus_dat_r) | ({32{slave_sel_r[1]}} & interface0_ram_bus_dat_r)) | ({32{slave_sel_r[2]}} & interface1_ram_bus_dat_r)) | ({32{slave_sel_r[3]}} & simsoc_dat_r));
    if (done) begin
        shared_dat_r <= 32'd4294967295;
    end
end
assign wait_1 = ((shared_stb & shared_cyc) & (~shared_ack));
always @(*) begin
    error <= 1'd0;
    if (done) begin
        error <= 1'd1;
    end
end
assign done = (count == 1'd0);
assign bus_errors_status = bus_errors;
assign picorv32_idbus_adr = picorv32_mem_addr;
assign picorv32_idbus_dat_w = picorv32_mem_wdata;
always @(*) begin
    picorv32_idbus_sel <= 4'd0;
    if ((picorv32_mem_wstrb != 1'd0)) begin
        picorv32_idbus_sel <= picorv32_mem_wstrb;
    end else begin
        picorv32_idbus_sel <= 4'd15;
    end
end
always @(*) begin
    picorv32_idbus_we <= 1'd0;
    if ((picorv32_mem_wstrb != 1'd0)) begin
        picorv32_idbus_we <= 1'd1;
    end else begin
        picorv32_idbus_we <= 1'd0;
    end
end
assign picorv32_idbus_cyc = picorv32_mem_valid;
assign picorv32_idbus_stb = picorv32_mem_valid;
assign picorv32_idbus_cti = 1'd0;
assign picorv32_idbus_bte = 1'd0;
assign picorv32_mem_ready = picorv32_idbus_ack;
assign picorv32_mem_rdata = picorv32_idbus_dat_r;
assign adr = ram_bus_adr[14:0];
assign ram_bus_dat_r = dat_r;
always @(*) begin
    sram0_we <= 4'd0;
    sram0_we[0] <= (((interface0_ram_bus_cyc & interface0_ram_bus_stb) & interface0_ram_bus_we) & interface0_ram_bus_sel[0]);
    sram0_we[1] <= (((interface0_ram_bus_cyc & interface0_ram_bus_stb) & interface0_ram_bus_we) & interface0_ram_bus_sel[1]);
    sram0_we[2] <= (((interface0_ram_bus_cyc & interface0_ram_bus_stb) & interface0_ram_bus_we) & interface0_ram_bus_sel[2]);
    sram0_we[3] <= (((interface0_ram_bus_cyc & interface0_ram_bus_stb) & interface0_ram_bus_we) & interface0_ram_bus_sel[3]);
end
assign sram0_adr = interface0_ram_bus_adr[10:0];
assign interface0_ram_bus_dat_r = sram0_dat_r;
assign sram0_dat_w = interface0_ram_bus_dat_w;
always @(*) begin
    sram1_we <= 4'd0;
    sram1_we[0] <= (((interface1_ram_bus_cyc & interface1_ram_bus_stb) & interface1_ram_bus_we) & interface1_ram_bus_sel[0]);
    sram1_we[1] <= (((interface1_ram_bus_cyc & interface1_ram_bus_stb) & interface1_ram_bus_we) & interface1_ram_bus_sel[1]);
    sram1_we[2] <= (((interface1_ram_bus_cyc & interface1_ram_bus_stb) & interface1_ram_bus_we) & interface1_ram_bus_sel[2]);
    sram1_we[3] <= (((interface1_ram_bus_cyc & interface1_ram_bus_stb) & interface1_ram_bus_we) & interface1_ram_bus_sel[3]);
end
assign sram1_adr = interface1_ram_bus_adr[13:0];
assign interface1_ram_bus_dat_r = sram1_dat_r;
assign sram1_dat_w = interface1_ram_bus_dat_w;
assign uart_phy_sink_valid = source_valid;
assign source_ready = uart_phy_sink_ready;
assign uart_phy_sink_first = source_first;
assign uart_phy_sink_last = source_last;
assign uart_phy_sink_payload_data = source_payload_data;
assign sink_valid = uart_phy_source_valid;
assign uart_phy_source_ready = sink_ready;
assign sink_first = uart_phy_source_first;
assign sink_last = uart_phy_source_last;
assign sink_payload_data = uart_phy_source_payload_data;
assign uart_tx_fifo_sink_valid = uart_rxtx_re;
assign uart_tx_fifo_sink_payload_data = uart_rxtx_r;
assign uart_phy_source_valid = uart_tx_fifo_source_valid;
assign uart_tx_fifo_source_ready = uart_phy_source_ready;
assign uart_phy_source_first = uart_tx_fifo_source_first;
assign uart_phy_source_last = uart_tx_fifo_source_last;
assign uart_phy_source_payload_data = uart_tx_fifo_source_payload_data;
assign uart_txfull_status = (~uart_tx_fifo_sink_ready);
assign uart_txempty_status = (~uart_tx_fifo_source_valid);
assign uart_tx_trigger = uart_tx_fifo_sink_ready;
assign uart_rx_fifo_sink_valid = uart_phy_sink_valid;
assign uart_phy_sink_ready = uart_rx_fifo_sink_ready;
assign uart_rx_fifo_sink_first = uart_phy_sink_first;
assign uart_rx_fifo_sink_last = uart_phy_sink_last;
assign uart_rx_fifo_sink_payload_data = uart_phy_sink_payload_data;
assign uart_rxtx_w = uart_rx_fifo_source_payload_data;
assign uart_rx_fifo_source_ready = uart_rx_clear;
assign uart_rxempty_status = (~uart_rx_fifo_source_valid);
assign uart_rxfull_status = (~uart_rx_fifo_sink_ready);
assign uart_rx_trigger = uart_rx_fifo_source_valid;
assign uart_txempty_tx0 = uart_tx_status;
assign uart_txempty_tx1 = uart_tx_pending;
always @(*) begin
    uart_tx_clear <= 1'd0;
    if ((uart_txempty_pending_re & uart_txempty_pending_r[0])) begin
        uart_tx_clear <= 1'd1;
    end
end
assign uart_txempty_rx0 = uart_rx_status;
assign uart_txempty_rx1 = uart_rx_pending;
always @(*) begin
    uart_rx_clear <= 1'd0;
    if ((uart_txempty_pending_re & uart_txempty_pending_r[1])) begin
        uart_rx_clear <= 1'd1;
    end
end
assign uart_irq = ((uart_txempty_pending_status[0] & uart_txempty_enable_storage[0]) | (uart_txempty_pending_status[1] & uart_txempty_enable_storage[1]));
assign uart_tx_status = uart_tx_trigger;
assign uart_tx_pending = uart_tx_trigger;
assign uart_rx_status = uart_rx_trigger;
assign uart_rx_pending = uart_rx_trigger;
assign serial_source_valid = sink_valid;
assign serial_source_data = sink_payload_data;
assign sink_ready = serial_source_ready;
assign source_valid = serial_sink_valid;
assign source_payload_data = serial_sink_data;
assign serial_sink_ready = source_ready;
assign uart_tx_fifo_level_din = {uart_tx_fifo_fifo_in_last, uart_tx_fifo_fifo_in_first, uart_tx_fifo_fifo_in_payload_data};
assign {uart_tx_fifo_fifo_out_last, uart_tx_fifo_fifo_out_first, uart_tx_fifo_fifo_out_payload_data} = uart_tx_fifo_level_dout;
assign {uart_tx_fifo_fifo_out_last, uart_tx_fifo_fifo_out_first, uart_tx_fifo_fifo_out_payload_data} = uart_tx_fifo_level_dout;
assign {uart_tx_fifo_fifo_out_last, uart_tx_fifo_fifo_out_first, uart_tx_fifo_fifo_out_payload_data} = uart_tx_fifo_level_dout;
assign uart_tx_fifo_sink_ready = uart_tx_fifo_level_writable;
assign uart_tx_fifo_level_we = uart_tx_fifo_sink_valid;
assign uart_tx_fifo_fifo_in_first = uart_tx_fifo_sink_first;
assign uart_tx_fifo_fifo_in_last = uart_tx_fifo_sink_last;
assign uart_tx_fifo_fifo_in_payload_data = uart_tx_fifo_sink_payload_data;
assign uart_tx_fifo_source_valid = uart_tx_fifo_readable;
assign uart_tx_fifo_source_first = uart_tx_fifo_fifo_out_first;
assign uart_tx_fifo_source_last = uart_tx_fifo_fifo_out_last;
assign uart_tx_fifo_source_payload_data = uart_tx_fifo_fifo_out_payload_data;
assign uart_tx_fifo_re = uart_tx_fifo_source_ready;
assign uart_tx_fifo_level_re = (uart_tx_fifo_level_readable & ((~uart_tx_fifo_readable) | uart_tx_fifo_re));
assign uart_tx_fifo_level1 = (uart_tx_fifo_level0 + uart_tx_fifo_readable);
always @(*) begin
    uart_tx_fifo_wrport_adr <= 4'd0;
    if (uart_tx_fifo_replace) begin
        uart_tx_fifo_wrport_adr <= (uart_tx_fifo_produce - 1'd1);
    end else begin
        uart_tx_fifo_wrport_adr <= uart_tx_fifo_produce;
    end
end
assign uart_tx_fifo_wrport_dat_w = uart_tx_fifo_level_din;
assign uart_tx_fifo_wrport_we = (uart_tx_fifo_level_we & (uart_tx_fifo_level_writable | uart_tx_fifo_replace));
assign uart_tx_fifo_do_read = (uart_tx_fifo_level_readable & uart_tx_fifo_level_re);
assign uart_tx_fifo_rdport_adr = uart_tx_fifo_consume;
assign uart_tx_fifo_level_dout = uart_tx_fifo_rdport_dat_r;
assign uart_tx_fifo_rdport_re = uart_tx_fifo_do_read;
assign uart_tx_fifo_level_writable = (uart_tx_fifo_level0 != 5'd16);
assign uart_tx_fifo_level_readable = (uart_tx_fifo_level0 != 1'd0);
assign uart_rx_fifo_level_din = {uart_rx_fifo_fifo_in_last, uart_rx_fifo_fifo_in_first, uart_rx_fifo_fifo_in_payload_data};
assign {uart_rx_fifo_fifo_out_last, uart_rx_fifo_fifo_out_first, uart_rx_fifo_fifo_out_payload_data} = uart_rx_fifo_level_dout;
assign {uart_rx_fifo_fifo_out_last, uart_rx_fifo_fifo_out_first, uart_rx_fifo_fifo_out_payload_data} = uart_rx_fifo_level_dout;
assign {uart_rx_fifo_fifo_out_last, uart_rx_fifo_fifo_out_first, uart_rx_fifo_fifo_out_payload_data} = uart_rx_fifo_level_dout;
assign uart_rx_fifo_sink_ready = uart_rx_fifo_level_writable;
assign uart_rx_fifo_level_we = uart_rx_fifo_sink_valid;
assign uart_rx_fifo_fifo_in_first = uart_rx_fifo_sink_first;
assign uart_rx_fifo_fifo_in_last = uart_rx_fifo_sink_last;
assign uart_rx_fifo_fifo_in_payload_data = uart_rx_fifo_sink_payload_data;
assign uart_rx_fifo_source_valid = uart_rx_fifo_readable;
assign uart_rx_fifo_source_first = uart_rx_fifo_fifo_out_first;
assign uart_rx_fifo_source_last = uart_rx_fifo_fifo_out_last;
assign uart_rx_fifo_source_payload_data = uart_rx_fifo_fifo_out_payload_data;
assign uart_rx_fifo_re = uart_rx_fifo_source_ready;
assign uart_rx_fifo_level_re = (uart_rx_fifo_level_readable & ((~uart_rx_fifo_readable) | uart_rx_fifo_re));
assign uart_rx_fifo_level1 = (uart_rx_fifo_level0 + uart_rx_fifo_readable);
always @(*) begin
    uart_rx_fifo_wrport_adr <= 4'd0;
    if (uart_rx_fifo_replace) begin
        uart_rx_fifo_wrport_adr <= (uart_rx_fifo_produce - 1'd1);
    end else begin
        uart_rx_fifo_wrport_adr <= uart_rx_fifo_produce;
    end
end
assign uart_rx_fifo_wrport_dat_w = uart_rx_fifo_level_din;
assign uart_rx_fifo_wrport_we = (uart_rx_fifo_level_we & (uart_rx_fifo_level_writable | uart_rx_fifo_replace));
assign uart_rx_fifo_do_read = (uart_rx_fifo_level_readable & uart_rx_fifo_level_re);
assign uart_rx_fifo_rdport_adr = uart_rx_fifo_consume;
assign uart_rx_fifo_level_dout = uart_rx_fifo_rdport_dat_r;
assign uart_rx_fifo_rdport_re = uart_rx_fifo_do_read;
assign uart_rx_fifo_level_writable = (uart_rx_fifo_level0 != 5'd16);
assign uart_rx_fifo_level_readable = (uart_rx_fifo_level0 != 1'd0);
assign timer_zero_trigger = (timer_value == 1'd0);
assign timer_value_zero0 = timer_zero_status;
assign timer_value_zero1 = timer_zero_pending;
always @(*) begin
    timer_zero_clear <= 1'd0;
    if ((timer_value_pending_re & timer_value_pending_r)) begin
        timer_zero_clear <= 1'd1;
    end
end
assign timer_irq = (timer_value_pending_status & timer_value_enable_storage);
assign timer_zero_status = timer_zero_trigger;
always @(*) begin
    simsoc_next_state <= 1'd0;
    simsoc_next_state <= simsoc_state;
    case (simsoc_state)
        1'd1: begin
            simsoc_next_state <= 1'd0;
        end
        default: begin
            if ((simsoc_cyc & simsoc_stb)) begin
                simsoc_next_state <= 1'd1;
            end
        end
    endcase
end
always @(*) begin
    simsoc_ack <= 1'd0;
    case (simsoc_state)
        1'd1: begin
            simsoc_ack <= 1'd1;
        end
        default: begin
        end
    endcase
end
always @(*) begin
    simsoc_csr_bridge_adr <= 14'd0;
    case (simsoc_state)
        1'd1: begin
        end
        default: begin
            if ((simsoc_cyc & simsoc_stb)) begin
                simsoc_csr_bridge_adr <= simsoc_adr;
            end
        end
    endcase
end
always @(*) begin
    simsoc_csr_bridge_re <= 1'd0;
    case (simsoc_state)
        1'd1: begin
        end
        default: begin
            if ((simsoc_cyc & simsoc_stb)) begin
                simsoc_csr_bridge_re <= ((~simsoc_we) & (simsoc_sel != 1'd0));
            end
        end
    endcase
end
always @(*) begin
    simsoc_csr_bridge_we <= 1'd0;
    case (simsoc_state)
        1'd1: begin
        end
        default: begin
            if ((simsoc_cyc & simsoc_stb)) begin
                simsoc_csr_bridge_we <= (simsoc_we & (simsoc_sel != 1'd0));
            end
        end
    endcase
end
always @(*) begin
    simsoc_csr_bridge_dat_w <= 32'd0;
    case (simsoc_state)
        1'd1: begin
        end
        default: begin
            simsoc_csr_bridge_dat_w <= simsoc_dat_w;
        end
    endcase
end
always @(*) begin
    simsoc_dat_r <= 32'd0;
    case (simsoc_state)
        1'd1: begin
            simsoc_dat_r <= simsoc_csr_bridge_dat_r;
        end
        default: begin
        end
    endcase
end
assign csr_bankarray_csrbank0_sel = (csr_bankarray_interface0_bank_bus_adr[13:9] == 1'd0);
assign csr_bankarray_csrbank0_sel_reset0_r = csr_bankarray_interface0_bank_bus_dat_w[1:0];
always @(*) begin
    csr_bankarray_csrbank0_sel_reset0_we <= 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd0))) begin
        csr_bankarray_csrbank0_sel_reset0_we <= csr_bankarray_interface0_bank_bus_re;
    end
end
always @(*) begin
    csr_bankarray_csrbank0_sel_reset0_re <= 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd0))) begin
        csr_bankarray_csrbank0_sel_reset0_re <= csr_bankarray_interface0_bank_bus_we;
    end
end
assign csr_bankarray_csrbank0_sel_scratch0_r = csr_bankarray_interface0_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank0_sel_scratch0_re <= 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank0_sel_scratch0_re <= csr_bankarray_interface0_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank0_sel_scratch0_we <= 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank0_sel_scratch0_we <= csr_bankarray_interface0_bank_bus_re;
    end
end
assign csr_bankarray_csrbank0_sel_bus_errors_r = csr_bankarray_interface0_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank0_sel_bus_errors_re <= 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank0_sel_bus_errors_re <= csr_bankarray_interface0_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank0_sel_bus_errors_we <= 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank0_sel_bus_errors_we <= csr_bankarray_interface0_bank_bus_re;
    end
end
always @(*) begin
    soc_rst <= 1'd0;
    if (reset_re) begin
        soc_rst <= reset_storage[0];
    end
end
assign reset_cpu_rst = reset_storage[1];
assign csr_bankarray_csrbank0_sel_reset0_w = reset_storage;
assign csr_bankarray_csrbank0_sel_scratch0_w = scratch_storage;
assign csr_bankarray_csrbank0_sel_bus_errors_w = bus_errors_status;
assign bus_errors_we = csr_bankarray_csrbank0_sel_bus_errors_we;
assign csr_bankarray_sel = (csr_bankarray_sram_bus_adr[13:9] == 1'd1);
always @(*) begin
    csr_bankarray_sram_bus_dat_r <= 32'd0;
    if (csr_bankarray_sel_r) begin
        csr_bankarray_sram_bus_dat_r <= csr_bankarray_dat_r;
    end
end
assign csr_bankarray_adr = csr_bankarray_sram_bus_adr[5:0];
assign csr_bankarray_csrbank1_sel = (csr_bankarray_interface1_bank_bus_adr[13:9] == 2'd2);
assign csr_bankarray_csrbank1_sel_load0_r = csr_bankarray_interface1_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank1_sel_load0_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd0))) begin
        csr_bankarray_csrbank1_sel_load0_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_load0_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd0))) begin
        csr_bankarray_csrbank1_sel_load0_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_sel_reload0_r = csr_bankarray_interface1_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank1_sel_reload0_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank1_sel_reload0_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_reload0_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank1_sel_reload0_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_sel_en0_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_sel_en0_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank1_sel_en0_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_en0_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank1_sel_en0_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
assign csr_bankarray_csrbank1_sel_update_value0_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_sel_update_value0_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 2'd3))) begin
        csr_bankarray_csrbank1_sel_update_value0_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_update_value0_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 2'd3))) begin
        csr_bankarray_csrbank1_sel_update_value0_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_sel_value_r = csr_bankarray_interface1_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank1_sel_value_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd4))) begin
        csr_bankarray_csrbank1_sel_value_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_value_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd4))) begin
        csr_bankarray_csrbank1_sel_value_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
assign csr_bankarray_csrbank1_sel_ev_status_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_sel_ev_status_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd5))) begin
        csr_bankarray_csrbank1_sel_ev_status_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_ev_status_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd5))) begin
        csr_bankarray_csrbank1_sel_ev_status_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
assign csr_bankarray_csrbank1_sel_ev_pending_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_sel_ev_pending_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd6))) begin
        csr_bankarray_csrbank1_sel_ev_pending_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_ev_pending_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd6))) begin
        csr_bankarray_csrbank1_sel_ev_pending_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_sel_ev_enable0_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_sel_ev_enable0_re <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd7))) begin
        csr_bankarray_csrbank1_sel_ev_enable0_re <= csr_bankarray_interface1_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank1_sel_ev_enable0_we <= 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd7))) begin
        csr_bankarray_csrbank1_sel_ev_enable0_we <= csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_sel_load0_w = timer_load_storage;
assign csr_bankarray_csrbank1_sel_reload0_w = timer_reload_storage;
assign csr_bankarray_csrbank1_sel_en0_w = timer_en_storage;
assign csr_bankarray_csrbank1_sel_update_value0_w = timer_update_value_storage;
assign csr_bankarray_csrbank1_sel_value_w = timer_value_status;
assign timer_value_we = csr_bankarray_csrbank1_sel_value_we;
assign timer_value_status_status = timer_value_zero0;
assign csr_bankarray_csrbank1_sel_ev_status_w = timer_value_status_status;
assign timer_value_status_we = csr_bankarray_csrbank1_sel_ev_status_we;
assign timer_value_pending_status = timer_value_zero1;
assign csr_bankarray_csrbank1_sel_ev_pending_w = timer_value_pending_status;
assign timer_value_pending_we = csr_bankarray_csrbank1_sel_ev_pending_we;
assign timer_value_zero2 = timer_value_enable_storage;
assign csr_bankarray_csrbank1_sel_ev_enable0_w = timer_value_enable_storage;
assign csr_bankarray_csrbank2_sel = (csr_bankarray_interface2_bank_bus_adr[13:9] == 2'd3);
assign uart_rxtx_r = csr_bankarray_interface2_bank_bus_dat_w[7:0];
always @(*) begin
    uart_rxtx_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd0))) begin
        uart_rxtx_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
always @(*) begin
    uart_rxtx_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd0))) begin
        uart_rxtx_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
assign csr_bankarray_csrbank2_sel_txfull_r = csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank2_sel_txfull_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank2_sel_txfull_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
always @(*) begin
    csr_bankarray_csrbank2_sel_txfull_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank2_sel_txfull_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
assign csr_bankarray_csrbank2_sel_rxempty_r = csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank2_sel_rxempty_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank2_sel_rxempty_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank2_sel_rxempty_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank2_sel_rxempty_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
assign csr_bankarray_csrbank2_sel_ev_status_r = csr_bankarray_interface2_bank_bus_dat_w[1:0];
always @(*) begin
    csr_bankarray_csrbank2_sel_ev_status_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd3))) begin
        csr_bankarray_csrbank2_sel_ev_status_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank2_sel_ev_status_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd3))) begin
        csr_bankarray_csrbank2_sel_ev_status_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
assign csr_bankarray_csrbank2_sel_ev_pending_r = csr_bankarray_interface2_bank_bus_dat_w[1:0];
always @(*) begin
    csr_bankarray_csrbank2_sel_ev_pending_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd4))) begin
        csr_bankarray_csrbank2_sel_ev_pending_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
always @(*) begin
    csr_bankarray_csrbank2_sel_ev_pending_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd4))) begin
        csr_bankarray_csrbank2_sel_ev_pending_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
assign csr_bankarray_csrbank2_sel_ev_enable0_r = csr_bankarray_interface2_bank_bus_dat_w[1:0];
always @(*) begin
    csr_bankarray_csrbank2_sel_ev_enable0_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd5))) begin
        csr_bankarray_csrbank2_sel_ev_enable0_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank2_sel_ev_enable0_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd5))) begin
        csr_bankarray_csrbank2_sel_ev_enable0_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
assign csr_bankarray_csrbank2_sel_txempty_r = csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank2_sel_txempty_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd6))) begin
        csr_bankarray_csrbank2_sel_txempty_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
always @(*) begin
    csr_bankarray_csrbank2_sel_txempty_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd6))) begin
        csr_bankarray_csrbank2_sel_txempty_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
assign csr_bankarray_csrbank2_sel_rxfull_r = csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank2_sel_rxfull_we <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd7))) begin
        csr_bankarray_csrbank2_sel_rxfull_we <= csr_bankarray_interface2_bank_bus_re;
    end
end
always @(*) begin
    csr_bankarray_csrbank2_sel_rxfull_re <= 1'd0;
    if ((csr_bankarray_csrbank2_sel & (csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd7))) begin
        csr_bankarray_csrbank2_sel_rxfull_re <= csr_bankarray_interface2_bank_bus_we;
    end
end
assign csr_bankarray_csrbank2_sel_txfull_w = uart_txfull_status;
assign uart_txfull_we = csr_bankarray_csrbank2_sel_txfull_we;
assign csr_bankarray_csrbank2_sel_rxempty_w = uart_rxempty_status;
assign uart_rxempty_we = csr_bankarray_csrbank2_sel_rxempty_we;
always @(*) begin
    uart_txempty_status_status <= 2'd0;
    uart_txempty_status_status[0] <= uart_txempty_tx0;
    uart_txempty_status_status[1] <= uart_txempty_rx0;
end
assign csr_bankarray_csrbank2_sel_ev_status_w = uart_txempty_status_status;
assign uart_txempty_status_we = csr_bankarray_csrbank2_sel_ev_status_we;
always @(*) begin
    uart_txempty_pending_status <= 2'd0;
    uart_txempty_pending_status[0] <= uart_txempty_tx1;
    uart_txempty_pending_status[1] <= uart_txempty_rx1;
end
assign csr_bankarray_csrbank2_sel_ev_pending_w = uart_txempty_pending_status;
assign uart_txempty_pending_we = csr_bankarray_csrbank2_sel_ev_pending_we;
assign uart_txempty_tx2 = uart_txempty_enable_storage[0];
assign uart_txempty_rx2 = uart_txempty_enable_storage[1];
assign csr_bankarray_csrbank2_sel_ev_enable0_w = uart_txempty_enable_storage;
assign csr_bankarray_csrbank2_sel_txempty_w = uart_txempty_status;
assign uart_txempty_we = csr_bankarray_csrbank2_sel_txempty_we;
assign csr_bankarray_csrbank2_sel_rxfull_w = uart_rxfull_status;
assign uart_rxfull_we = csr_bankarray_csrbank2_sel_rxfull_we;
assign csr_interconnect_adr = simsoc_csr_bridge_adr;
assign csr_interconnect_re = simsoc_csr_bridge_re;
assign csr_interconnect_we = simsoc_csr_bridge_we;
assign csr_interconnect_dat_w = simsoc_csr_bridge_dat_w;
assign simsoc_csr_bridge_dat_r = csr_interconnect_dat_r;
assign csr_bankarray_interface0_bank_bus_adr = csr_interconnect_adr;
assign csr_bankarray_interface1_bank_bus_adr = csr_interconnect_adr;
assign csr_bankarray_interface2_bank_bus_adr = csr_interconnect_adr;
assign csr_bankarray_sram_bus_adr = csr_interconnect_adr;
assign csr_bankarray_interface0_bank_bus_re = csr_interconnect_re;
assign csr_bankarray_interface1_bank_bus_re = csr_interconnect_re;
assign csr_bankarray_interface2_bank_bus_re = csr_interconnect_re;
assign csr_bankarray_sram_bus_re = csr_interconnect_re;
assign csr_bankarray_interface0_bank_bus_we = csr_interconnect_we;
assign csr_bankarray_interface1_bank_bus_we = csr_interconnect_we;
assign csr_bankarray_interface2_bank_bus_we = csr_interconnect_we;
assign csr_bankarray_sram_bus_we = csr_interconnect_we;
assign csr_bankarray_interface0_bank_bus_dat_w = csr_interconnect_dat_w;
assign csr_bankarray_interface1_bank_bus_dat_w = csr_interconnect_dat_w;
assign csr_bankarray_interface2_bank_bus_dat_w = csr_interconnect_dat_w;
assign csr_bankarray_sram_bus_dat_w = csr_interconnect_dat_w;
assign csr_interconnect_dat_r = (((csr_bankarray_interface0_bank_bus_dat_r | csr_bankarray_interface1_bank_bus_dat_r) | csr_bankarray_interface2_bank_bus_dat_r) | csr_bankarray_sram_bus_dat_r);
always @(*) begin
    array_muxed0 <= 30'd0;
    case (grant)
        default: begin
            array_muxed0 <= adapted_interface_adr;
        end
    endcase
end
always @(*) begin
    array_muxed1 <= 32'd0;
    case (grant)
        default: begin
            array_muxed1 <= adapted_interface_dat_w;
        end
    endcase
end
always @(*) begin
    array_muxed2 <= 4'd0;
    case (grant)
        default: begin
            array_muxed2 <= adapted_interface_sel;
        end
    endcase
end
always @(*) begin
    array_muxed3 <= 1'd0;
    case (grant)
        default: begin
            array_muxed3 <= adapted_interface_cyc;
        end
    endcase
end
always @(*) begin
    array_muxed4 <= 1'd0;
    case (grant)
        default: begin
            array_muxed4 <= adapted_interface_stb;
        end
    endcase
end
always @(*) begin
    array_muxed5 <= 1'd0;
    case (grant)
        default: begin
            array_muxed5 <= adapted_interface_we;
        end
    endcase
end
always @(*) begin
    array_muxed6 <= 3'd0;
    case (grant)
        default: begin
            array_muxed6 <= adapted_interface_cti;
        end
    endcase
end
always @(*) begin
    array_muxed7 <= 2'd0;
    case (grant)
        default: begin
            array_muxed7 <= adapted_interface_bte;
        end
    endcase
end


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge por_clk) begin
    crg_int_rst <= 1'd0;
end

always @(posedge sys_clk_1) begin
    slave_sel_r <= slave_sel;
    if (wait_1) begin
        if ((~done)) begin
            count <= (count - 1'd1);
        end
    end else begin
        count <= 20'd1000000;
    end
    if ((bus_errors != 32'd4294967295)) begin
        if (bus_error) begin
            bus_errors <= (bus_errors + 1'd1);
        end
    end
    ram_bus_ack <= 1'd0;
    if (((ram_bus_cyc & ram_bus_stb) & ((~ram_bus_ack) | adr_burst))) begin
        ram_bus_ack <= 1'd1;
    end
    interface0_ram_bus_ack <= 1'd0;
    if (((interface0_ram_bus_cyc & interface0_ram_bus_stb) & ((~interface0_ram_bus_ack) | sram0_adr_burst))) begin
        interface0_ram_bus_ack <= 1'd1;
    end
    interface1_ram_bus_ack <= 1'd0;
    if (((interface1_ram_bus_cyc & interface1_ram_bus_stb) & ((~interface1_ram_bus_ack) | sram1_adr_burst))) begin
        interface1_ram_bus_ack <= 1'd1;
    end
    if (uart_tx_fifo_level_re) begin
        uart_tx_fifo_readable <= 1'd1;
    end else begin
        if (uart_tx_fifo_re) begin
            uart_tx_fifo_readable <= 1'd0;
        end
    end
    if (((uart_tx_fifo_level_we & uart_tx_fifo_level_writable) & (~uart_tx_fifo_replace))) begin
        uart_tx_fifo_produce <= (uart_tx_fifo_produce + 1'd1);
    end
    if (uart_tx_fifo_do_read) begin
        uart_tx_fifo_consume <= (uart_tx_fifo_consume + 1'd1);
    end
    if (((uart_tx_fifo_level_we & uart_tx_fifo_level_writable) & (~uart_tx_fifo_replace))) begin
        if ((~uart_tx_fifo_do_read)) begin
            uart_tx_fifo_level0 <= (uart_tx_fifo_level0 + 1'd1);
        end
    end else begin
        if (uart_tx_fifo_do_read) begin
            uart_tx_fifo_level0 <= (uart_tx_fifo_level0 - 1'd1);
        end
    end
    if (uart_rx_fifo_level_re) begin
        uart_rx_fifo_readable <= 1'd1;
    end else begin
        if (uart_rx_fifo_re) begin
            uart_rx_fifo_readable <= 1'd0;
        end
    end
    if (((uart_rx_fifo_level_we & uart_rx_fifo_level_writable) & (~uart_rx_fifo_replace))) begin
        uart_rx_fifo_produce <= (uart_rx_fifo_produce + 1'd1);
    end
    if (uart_rx_fifo_do_read) begin
        uart_rx_fifo_consume <= (uart_rx_fifo_consume + 1'd1);
    end
    if (((uart_rx_fifo_level_we & uart_rx_fifo_level_writable) & (~uart_rx_fifo_replace))) begin
        if ((~uart_rx_fifo_do_read)) begin
            uart_rx_fifo_level0 <= (uart_rx_fifo_level0 + 1'd1);
        end
    end else begin
        if (uart_rx_fifo_do_read) begin
            uart_rx_fifo_level0 <= (uart_rx_fifo_level0 - 1'd1);
        end
    end
    if (timer_en_storage) begin
        if ((timer_value == 1'd0)) begin
            timer_value <= timer_reload_storage;
        end else begin
            timer_value <= (timer_value - 1'd1);
        end
    end else begin
        timer_value <= timer_load_storage;
    end
    if (timer_update_value_re) begin
        timer_value_status <= timer_value;
    end
    if (timer_zero_clear) begin
        timer_zero_pending <= 1'd0;
    end
    timer_zero_trigger_d <= timer_zero_trigger;
    if ((timer_zero_trigger & (~timer_zero_trigger_d))) begin
        timer_zero_pending <= 1'd1;
    end
    simsoc_state <= simsoc_next_state;
    csr_bankarray_interface0_bank_bus_dat_r <= 1'd0;
    if (csr_bankarray_csrbank0_sel) begin
        case (csr_bankarray_interface0_bank_bus_adr[8:0])
            1'd0: begin
                csr_bankarray_interface0_bank_bus_dat_r <= csr_bankarray_csrbank0_sel_reset0_w;
            end
            1'd1: begin
                csr_bankarray_interface0_bank_bus_dat_r <= csr_bankarray_csrbank0_sel_scratch0_w;
            end
            2'd2: begin
                csr_bankarray_interface0_bank_bus_dat_r <= csr_bankarray_csrbank0_sel_bus_errors_w;
            end
        endcase
    end
    if (csr_bankarray_csrbank0_sel_reset0_re) begin
        reset_storage <= csr_bankarray_csrbank0_sel_reset0_r;
    end
    reset_re <= csr_bankarray_csrbank0_sel_reset0_re;
    if (csr_bankarray_csrbank0_sel_scratch0_re) begin
        scratch_storage <= csr_bankarray_csrbank0_sel_scratch0_r;
    end
    scratch_re <= csr_bankarray_csrbank0_sel_scratch0_re;
    bus_errors_re <= csr_bankarray_csrbank0_sel_bus_errors_re;
    csr_bankarray_sel_r <= csr_bankarray_sel;
    csr_bankarray_interface1_bank_bus_dat_r <= 1'd0;
    if (csr_bankarray_csrbank1_sel) begin
        case (csr_bankarray_interface1_bank_bus_adr[8:0])
            1'd0: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_load0_w;
            end
            1'd1: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_reload0_w;
            end
            2'd2: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_en0_w;
            end
            2'd3: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_update_value0_w;
            end
            3'd4: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_value_w;
            end
            3'd5: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_ev_status_w;
            end
            3'd6: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_ev_pending_w;
            end
            3'd7: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_sel_ev_enable0_w;
            end
        endcase
    end
    if (csr_bankarray_csrbank1_sel_load0_re) begin
        timer_load_storage <= csr_bankarray_csrbank1_sel_load0_r;
    end
    timer_load_re <= csr_bankarray_csrbank1_sel_load0_re;
    if (csr_bankarray_csrbank1_sel_reload0_re) begin
        timer_reload_storage <= csr_bankarray_csrbank1_sel_reload0_r;
    end
    timer_reload_re <= csr_bankarray_csrbank1_sel_reload0_re;
    if (csr_bankarray_csrbank1_sel_en0_re) begin
        timer_en_storage <= csr_bankarray_csrbank1_sel_en0_r;
    end
    timer_en_re <= csr_bankarray_csrbank1_sel_en0_re;
    if (csr_bankarray_csrbank1_sel_update_value0_re) begin
        timer_update_value_storage <= csr_bankarray_csrbank1_sel_update_value0_r;
    end
    timer_update_value_re <= csr_bankarray_csrbank1_sel_update_value0_re;
    timer_value_re <= csr_bankarray_csrbank1_sel_value_re;
    timer_value_status_re <= csr_bankarray_csrbank1_sel_ev_status_re;
    if (csr_bankarray_csrbank1_sel_ev_pending_re) begin
        timer_value_pending_r <= csr_bankarray_csrbank1_sel_ev_pending_r;
    end
    timer_value_pending_re <= csr_bankarray_csrbank1_sel_ev_pending_re;
    if (csr_bankarray_csrbank1_sel_ev_enable0_re) begin
        timer_value_enable_storage <= csr_bankarray_csrbank1_sel_ev_enable0_r;
    end
    timer_value_enable_re <= csr_bankarray_csrbank1_sel_ev_enable0_re;
    csr_bankarray_interface2_bank_bus_dat_r <= 1'd0;
    if (csr_bankarray_csrbank2_sel) begin
        case (csr_bankarray_interface2_bank_bus_adr[8:0])
            1'd0: begin
                csr_bankarray_interface2_bank_bus_dat_r <= uart_rxtx_w;
            end
            1'd1: begin
                csr_bankarray_interface2_bank_bus_dat_r <= csr_bankarray_csrbank2_sel_txfull_w;
            end
            2'd2: begin
                csr_bankarray_interface2_bank_bus_dat_r <= csr_bankarray_csrbank2_sel_rxempty_w;
            end
            2'd3: begin
                csr_bankarray_interface2_bank_bus_dat_r <= csr_bankarray_csrbank2_sel_ev_status_w;
            end
            3'd4: begin
                csr_bankarray_interface2_bank_bus_dat_r <= csr_bankarray_csrbank2_sel_ev_pending_w;
            end
            3'd5: begin
                csr_bankarray_interface2_bank_bus_dat_r <= csr_bankarray_csrbank2_sel_ev_enable0_w;
            end
            3'd6: begin
                csr_bankarray_interface2_bank_bus_dat_r <= csr_bankarray_csrbank2_sel_txempty_w;
            end
            3'd7: begin
                csr_bankarray_interface2_bank_bus_dat_r <= csr_bankarray_csrbank2_sel_rxfull_w;
            end
        endcase
    end
    uart_txfull_re <= csr_bankarray_csrbank2_sel_txfull_re;
    uart_rxempty_re <= csr_bankarray_csrbank2_sel_rxempty_re;
    uart_txempty_status_re <= csr_bankarray_csrbank2_sel_ev_status_re;
    if (csr_bankarray_csrbank2_sel_ev_pending_re) begin
        uart_txempty_pending_r <= csr_bankarray_csrbank2_sel_ev_pending_r;
    end
    uart_txempty_pending_re <= csr_bankarray_csrbank2_sel_ev_pending_re;
    if (csr_bankarray_csrbank2_sel_ev_enable0_re) begin
        uart_txempty_enable_storage <= csr_bankarray_csrbank2_sel_ev_enable0_r;
    end
    uart_txempty_enable_re <= csr_bankarray_csrbank2_sel_ev_enable0_re;
    uart_txempty_re <= csr_bankarray_csrbank2_sel_txempty_re;
    uart_rxfull_re <= csr_bankarray_csrbank2_sel_rxfull_re;
    if (sys_rst) begin
        reset_storage <= 2'd0;
        reset_re <= 1'd0;
        scratch_storage <= 32'd305419896;
        scratch_re <= 1'd0;
        bus_errors_re <= 1'd0;
        bus_errors <= 32'd0;
        ram_bus_ack <= 1'd0;
        interface0_ram_bus_ack <= 1'd0;
        interface1_ram_bus_ack <= 1'd0;
        uart_txfull_re <= 1'd0;
        uart_rxempty_re <= 1'd0;
        uart_txempty_status_re <= 1'd0;
        uart_txempty_pending_re <= 1'd0;
        uart_txempty_pending_r <= 2'd0;
        uart_txempty_enable_storage <= 2'd0;
        uart_txempty_enable_re <= 1'd0;
        uart_txempty_re <= 1'd0;
        uart_rxfull_re <= 1'd0;
        uart_tx_fifo_readable <= 1'd0;
        uart_tx_fifo_level0 <= 5'd0;
        uart_tx_fifo_produce <= 4'd0;
        uart_tx_fifo_consume <= 4'd0;
        uart_rx_fifo_readable <= 1'd0;
        uart_rx_fifo_level0 <= 5'd0;
        uart_rx_fifo_produce <= 4'd0;
        uart_rx_fifo_consume <= 4'd0;
        timer_load_storage <= 32'd0;
        timer_load_re <= 1'd0;
        timer_reload_storage <= 32'd0;
        timer_reload_re <= 1'd0;
        timer_en_storage <= 1'd0;
        timer_en_re <= 1'd0;
        timer_update_value_storage <= 1'd0;
        timer_update_value_re <= 1'd0;
        timer_value_status <= 32'd0;
        timer_value_re <= 1'd0;
        timer_zero_pending <= 1'd0;
        timer_zero_trigger_d <= 1'd0;
        timer_value_status_re <= 1'd0;
        timer_value_pending_re <= 1'd0;
        timer_value_pending_r <= 1'd0;
        timer_value_enable_storage <= 1'd0;
        timer_value_enable_re <= 1'd0;
        timer_value <= 32'd0;
        slave_sel_r <= 4'd0;
        count <= 20'd1000000;
        csr_bankarray_sel_r <= 1'd0;
        simsoc_state <= 1'd0;
    end
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Memory rom: 32768-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [31:0] rom[0:32767];
initial begin
	$readmemh("sim_rom.init", rom);
end
reg [31:0] rom_dat0;
always @(posedge sys_clk_1) begin
	rom_dat0 <= rom[adr];
end
assign dat_r = rom_dat0;


//------------------------------------------------------------------------------
// Memory sram: 2048-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8
reg [31:0] sram[0:2047];
initial begin
	$readmemh("sim_sram.init", sram);
end
reg [10:0] sram_adr0;
always @(posedge sys_clk_1) begin : mem_write_block
	integer we_index;
	for(we_index = 0; we_index < 4; we_index=we_index+1)
		if (sram0_we[we_index])
			sram[sram0_adr][we_index*8 +: 8] <= sram0_dat_w[we_index*8 +: 8];
	sram_adr0 <= sram0_adr;
end
assign sram0_dat_r = sram[sram_adr0];


//------------------------------------------------------------------------------
// Memory main_ram: 16384-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8
reg [31:0] main_ram[0:16383];
initial begin
	$readmemh("sim_main_ram.init", main_ram);
end
reg [13:0] main_ram_adr0;
always @(posedge sys_clk_1) begin : mem_write_block_1
	integer we_index_1;
	for(we_index_1 = 0; we_index_1 < 4; we_index_1=we_index_1+1)
		if (sram1_we[we_index_1])
			main_ram[sram1_adr][we_index_1*8 +: 8] <= sram1_dat_w[we_index_1*8 +: 8];
	main_ram_adr0 <= sram1_adr;
end
assign sram1_dat_r = main_ram[main_ram_adr0];


//------------------------------------------------------------------------------
// Memory mem: 37-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] mem[0:36];
initial begin
	$readmemh("sim_mem.init", mem);
end
reg [5:0] mem_adr0;
always @(posedge sys_clk_1) begin
	mem_adr0 <= csr_bankarray_adr;
end
assign csr_bankarray_dat_r = mem[mem_adr0];


//------------------------------------------------------------------------------
// Memory storage: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage[0:15];
reg [9:0] storage_dat0;
reg [9:0] storage_dat1;
always @(posedge sys_clk_1) begin
	if (uart_tx_fifo_wrport_we)
		storage[uart_tx_fifo_wrport_adr] <= uart_tx_fifo_wrport_dat_w;
	storage_dat0 <= storage[uart_tx_fifo_wrport_adr];
end
always @(posedge sys_clk_1) begin
	if (uart_tx_fifo_rdport_re)
		storage_dat1 <= storage[uart_tx_fifo_rdport_adr];
end
assign uart_tx_fifo_wrport_dat_r = storage_dat0;
assign uart_tx_fifo_rdport_dat_r = storage_dat1;


//------------------------------------------------------------------------------
// Memory storage_1: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage_1[0:15];
reg [9:0] storage_1_dat0;
reg [9:0] storage_1_dat1;
always @(posedge sys_clk_1) begin
	if (uart_rx_fifo_wrport_we)
		storage_1[uart_rx_fifo_wrport_adr] <= uart_rx_fifo_wrport_dat_w;
	storage_1_dat0 <= storage_1[uart_rx_fifo_wrport_adr];
end
always @(posedge sys_clk_1) begin
	if (uart_rx_fifo_rdport_re)
		storage_1_dat1 <= storage_1[uart_rx_fifo_rdport_adr];
end
assign uart_rx_fifo_wrport_dat_r = storage_1_dat0;
assign uart_rx_fifo_rdport_dat_r = storage_1_dat1;


//------------------------------------------------------------------------------
// Instance picorv32 of picorv32 Module.
//------------------------------------------------------------------------------
picorv32 #(
	// Parameters.
	.CATCH_ILLINSN        (1'd1),
	.CATCH_MISALIGN       (1'd1),
	.ENABLE_COUNTERS      (1'd1),
	.ENABLE_COUNTERS64    (1'd1),
	.ENABLE_DIV           (1'd1),
	.ENABLE_FAST_MUL      (1'd0),
	.ENABLE_IRQ           (1'd1),
	.ENABLE_IRQ_QREGS     (1'd1),
	.ENABLE_IRQ_TIMER     (1'd1),
	.ENABLE_MUL           (1'd1),
	.ENABLE_PCPI          (1'd0),
	.ENABLE_REGS_16_31    (1'd1),
	.ENABLE_REGS_DUALPORT (1'd1),
	.ENABLE_TRACE         (1'd0),
	.LATCHED_IRQ          (32'd4294967295),
	.LATCHED_MEM_RDATA    (1'd0),
	.MASKED_IRQ           (1'd0),
	.PROGADDR_IRQ         (5'd16),
	.PROGADDR_RESET       (1'd0),
	.STACKADDR            (32'd4294967295),
	.TWO_CYCLE_ALU        (1'd0),
	.TWO_CYCLE_COMPARE    (1'd0),
	.TWO_STAGE_SHIFT      (1'd1)
) picorv32 (
	// Inputs.
	.clk          (sys_clk_1),
	.irq          (picorv32_interrupt),
	.mem_rdata    (picorv32_mem_rdata),
	.mem_ready    (picorv32_mem_ready),
	.pcpi_rd      (1'd0),
	.pcpi_ready   (1'd0),
	.pcpi_wait    (1'd0),
	.pcpi_wr      (1'd0),
	.resetn       ((~(sys_rst | picorv32_reset))),

	// Outputs.
	.eoi          (picorv329),
	.mem_addr     (picorv32_mem_addr),
	.mem_instr    (picorv32_mem_instr),
	.mem_la_addr  (picorv322),
	.mem_la_read  (picorv320),
	.mem_la_wdata (picorv323),
	.mem_la_write (picorv321),
	.mem_la_wstrb (picorv324),
	.mem_valid    (picorv32_mem_valid),
	.mem_wdata    (picorv32_mem_wdata),
	.mem_wstrb    (picorv32_mem_wstrb),
	.pcpi_insn    (picorv326),
	.pcpi_rs1     (picorv327),
	.pcpi_rs2     (picorv328),
	.pcpi_valid   (picorv325),
	.trap         (picorv32_trap)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2026-03-26 14:47:40.
//------------------------------------------------------------------------------

module sim_1core(
    input sys_clk,
    input [7:0] serial_sink_data_0,
    output serial_sink_ready_0,
    input serial_sink_valid_0,
    output [7:0] serial_source_data_0,
    input serial_source_ready_0,
    output serial_source_valid_0,
    output [7:0] shared_bus_data
);

    // Shared bus: aggregate all cores' UART output → feed back as input
    // This forces all cores to be evaluated every cycle (no dead code)
    wire [7:0] bus_data;
    assign bus_data = serial_source_data_0;
    assign shared_bus_data = bus_data;


    wire [7:0] core0_sink_data;
    assign core0_sink_data = serial_sink_data_0 ^ bus_data;
    sim_core core0(
        .serial_sink_data(core0_sink_data),
        .serial_sink_ready(serial_sink_ready_0),
        .serial_sink_valid(serial_sink_valid_0 | (|bus_data)),
        .serial_source_data(serial_source_data_0),
        .serial_source_ready(serial_source_ready_0),
        .serial_source_valid(serial_source_valid_0),
        .sys_clk(sys_clk)
    );
endmodule
